import os, os.path, re

pattern = re.compile("void\s+(onspawn|ai|ondeath)_(\w+)")

matches = []
for fn in os.listdir("src/ai"):
	if os.path.isfile("src/ai/" + fn):
		with open("src/ai/" + fn, "r") as f:
			matches += pattern.findall(f.read())
			#print(matches)

with open("inc/ai_gen.h", "w") as header:
	header.write("// Generated by aigen.py - do not edit\n")
	header.write("#include \"entity.h\"\n\n")
	for m in matches:
		header.write("void " + m[0] + "_" + m[1] + "(Entity *);\n")
