# For compatibility

.PHONY: all ntsc ntsc-debug pal pal-debug release debug clean

all:
	make
ntsc:
	make
ntsc-debug:
	make debug
pal:
	make
pal-debug:
	make debug
release:
	make release
debug:
	make debug
clean:
	make clean
