# For compatibility

.PHONY: all ntsc ntsc-debug pal pal-debug release debug clean

all:
	make
ntsc:
	make ntsc
ntsc-debug:
	make ntsc-debug
pal:
	make pal
pal-debug:
	make pal-debug
release:
	make release
debug:
	make debug
clean:
	make clean
