#include "md/types.h"

#include "res/stage.h"
#include "res/pal.h"
#include "resources.h"
#include "md/vdp.h"

#include "tables.h"

// Keep wait times divisible by 16

// Determines which member of the union in credits_info is used
enum CreditCmd {
	TEXT,		// Add a string of text ([)
	ICON,		// Show an icon from casts.pbm (])
	WAIT,		// Delay until next instruction (-)
	MOVE,		// Sets the text X position (+)
	SONG,		// Change the music (!)
	SONG_FADE,	// Fade out music (~)
	FLAG_JUMP,	// Jump to label if a flag is set (f)
	JUMP,		// Jump to label (j)
	LABEL,		// Label that can be jumped to (l)
	PALETTE,	// Swap one of the palettes (no CS equivalent)
	LOADPXE,    // Load 0.pxe
	END,		// Stop scrolling and pause indefinitely (/)
};

#define C_TEXT(str, jstr)	{ .cmd = TEXT, .text = { /*str,*/ jstr } }
#define C_ICON(id, pal)		{ .cmd = ICON, .icon = { id, pal } }
#define C_WAIT(ticks)		{ .cmd = WAIT, .wait = { ticks } }
#define C_SONG(id)			{ .cmd = SONG, .song = { id } }
#define C_SONG_FADE()		{ .cmd = SONG_FADE }
#define C_FLAG_JUMP(f, l)	{ .cmd = FLAG_JUMP, .fjump = { f, l } }
#define C_JUMP(l)			{ .cmd = JUMP, .jump = { l } }
#define C_LABEL(n)			{ .cmd = LABEL, .label = { n } }
#define C_MOVE(x)			{ .cmd = MOVE, .move = { x } }
#define C_LOADPXE()			{ .cmd = LOADPXE }
#define C_END()				{ .cmd = END }

enum Casts {
	SUE,		KAZUMA,		MOMORIN,	BOOSTER,	ITOH,		DOCTOR,
	CURLY,		COLON,		JENKA,		PUPPY,		MISERY,		BALROG,
	TOROKO,		KING,		JACK,		MAHIN,		SANTA,		CHACO,
	SANDAIME,	KANPACHI,	SHOVELBR,	MEGANE,		CHIE,		ZETT,
	MALCO,		ROBOT,		CHABA,		GERO,		HASUMI,		POOHBLK,
	LITTLES,	CTHULHU,	BA2,		SKYDRAGN,	GUNSMITH,	MUSIC,
	DEBUGCAT,	CHINFISH,	CRITTER,	BAT,		THEDOOR,	PIGNON,
	GPIGNON,	GKEEPER,	MAPIGNON,	BEETLE,		BASU,		BEHEMOTH,
	BASIL,		PCRITTER,	MANNAN,		JELLY,		KULALA,		PUCHI,
	FROG,		PRESS,		RAVIL,		BABY,		POLISH,		ARMADILL,
	SANDCROC,	SKELETON,	SKULHEAD,	CROW,		SKULSTEP,	FLOWER,
	GAUDI,		ARMOR,		GAUDIEGG,	MONSTERX,	FIREWHIR,	BUYO,
	BUYOBASE,	FUZZ,		FUZZCORE,	BLOWFISH,	IRONHEAD,	CNTRBOMB,
	DRAGONZ,	SISTERS,	NIGHTSPR,	HOPPY,		ORANGEBL,	DROLL,
	MIDORIN,	GUNFISH,	STUMPY,		NUMAHCHI,	REDDEMON,	IGOR,
	ROLLING,	DELEET,		BUTE,		MESA,		GRNDEVIL,	BALLOS,
	BALFROG,	OMEGA,		CORE,		UNDCORE,	TOROKOF,	DOCTORF,
	BALLOS2,	HVPRESS,	NAO,		KUROI,		OKAMI,		SWORD,
	GIDEON,		THANKS,
};

const credits_info_def credits_info[] = {
	C_MOVE(144),
	C_SONG(33),
	C_TEXT("  = CAST =  ",			1),
	C_WAIT(320),
	C_TEXT("- Surface Dwellers -",	2),						C_WAIT(64),
	C_TEXT("Plucky, looks up",		3), 					C_WAIT(16),
	C_TEXT(" to her brother",		4),						C_WAIT(16),
	C_TEXT("  Sue Sakamoto",		5),	C_ICON(SUE,		3), C_WAIT(64),
	C_TEXT("Her occasionally",		6),	 					C_WAIT(16),
	C_TEXT(" reliable brother",		7),						C_WAIT(16),
	C_TEXT("  Kazuma Sakamoto",		8),	C_ICON(KAZUMA,	3), C_WAIT(64),
	C_TEXT("Sue's Mother",			9), 					C_WAIT(16),
	C_TEXT("-",						10), 					C_WAIT(16),
	C_TEXT("  Momorin Sakamoto",	11),C_ICON(MOMORIN,	3), C_WAIT(64),
	C_TEXT("Sue's Grandfather",		12), 					C_WAIT(16),
	C_TEXT(" figure",				13), 					C_WAIT(16),
	C_TEXT("  Booster",				14),C_ICON(BOOSTER,	3), C_WAIT(64),
	C_TEXT("The Mimiga-shaped",		15), 					C_WAIT(16),
	C_TEXT(" coward",				16), 					C_WAIT(16),
	C_TEXT("  Itoh",				17),C_ICON(ITOH,	3), C_WAIT(64),
	C_WAIT(64),
	C_TEXT("- Mimiga Village -",	18),					C_WAIT(64),
	C_TEXT("Sweet and brave",		19), 					C_WAIT(16),
	C_TEXT("-",						20), 					C_WAIT(16),
	C_TEXT("  Toroko",				21),C_ICON(TOROKO,	3), C_WAIT(64),
	C_TEXT("The village leader",	22), 					C_WAIT(16),
	C_TEXT("-",						23), 					C_WAIT(16),
	C_TEXT("  King",				24),C_ICON(KING,	3), C_WAIT(64),
	C_TEXT("The Number-Two",		25), 					C_WAIT(16),
	C_TEXT("-",						26), 					C_WAIT(16),
	C_TEXT("  Jack",				27),C_ICON(JACK,	3), C_WAIT(64),
	C_TEXT("Never stops eating",	28), 					C_WAIT(16),
	C_TEXT("-",						29), 					C_WAIT(16),
	C_TEXT("  Mahin",				30),C_ICON(MAHIN,	3), C_WAIT(64),
	C_TEXT("Loves to fish",			31), 					C_WAIT(16),
	C_TEXT("-",						32), 					C_WAIT(16),
	C_TEXT("  Kanpachi",			33),C_ICON(KANPACHI,3), C_WAIT(64),
	C_TEXT("Mans the farm",			34), 					C_WAIT(16),
	C_TEXT("-",						35), 					C_WAIT(16),
	C_TEXT("  Sandaime",			36),C_ICON(SANDAIME,3), C_WAIT(64),
	C_WAIT(64),
	C_TEXT("- Grasstown -",			37),					C_WAIT(64),
	C_TEXT("Lives alone",			38), 					C_WAIT(16),
	C_TEXT("-",						39), 					C_WAIT(16),
	C_TEXT("  Santa",				40),C_ICON(SANTA,	3), C_WAIT(64),
	C_TEXT("The colorful Mimiga",	41), 					C_WAIT(16),
	C_TEXT("-",						42), 					C_WAIT(16),
	C_TEXT("  Chaco",				43),C_ICON(CHACO,	3), C_WAIT(64),
	C_TEXT("Power Room watcher",	44), 					C_WAIT(16),
	C_TEXT("-",						45), 					C_WAIT(16),
	C_TEXT("  Malco",				46),C_ICON(MALCO,	3), C_WAIT(64),
	C_WAIT(64),
	C_TEXT("- Sand Zone -",			47),					C_WAIT(64),
	C_TEXT("Ally of the Mimigas",	48), 					C_WAIT(16),
	C_TEXT("-",						49), 					C_WAIT(16),
	C_TEXT("  Curly",				50),C_ICON(CURLY,	3), C_WAIT(64),
	C_TEXT("Raised by Curly",		51), 					C_WAIT(16),
	C_TEXT("-",						52), 					C_WAIT(16),
	C_TEXT("  Colon",				53),C_ICON(COLON,	3), C_WAIT(64),
	C_TEXT("Original keeper of",	54), 					C_WAIT(16),
	C_TEXT(" the Sand Zone",		55), 					C_WAIT(16),
	C_TEXT("  Jenka",				56),C_ICON(JENKA,	3), C_WAIT(64),
	C_WAIT(32),
	C_TEXT("Jenka's Puppies",		57), 					C_WAIT(32),
	C_TEXT("  Hajime",				58),C_ICON(PUPPY,	3), C_WAIT(32),
	C_TEXT("  Shinobu",				59),C_ICON(PUPPY,	3), C_WAIT(32),
	C_TEXT("  Kakeru",				60),C_ICON(PUPPY,	3), C_WAIT(32),
	C_TEXT("  Mick",				61),C_ICON(PUPPY,	3), C_WAIT(32),
	C_TEXT("  Nene",				62),C_ICON(PUPPY,	3), C_WAIT(64),
	C_WAIT(64),
	C_TEXT("- Labyrinth -",			63),					C_WAIT(64),
	C_TEXT("The labyrinth's",		64), 					C_WAIT(16),
	C_TEXT(" weapons dealer",		65), 					C_WAIT(16),
	C_TEXT("  Chaba",				66),C_ICON(CHABA,	3), C_WAIT(64),
	C_TEXT("The labyrinth's",		67), 					C_WAIT(16),
	C_TEXT(" resident physician",	68), 					C_WAIT(16),
	C_TEXT("  Dr. Gero",			69),C_ICON(GERO,	3), C_WAIT(64),
	C_TEXT("I am a nurse!",			70), 					C_WAIT(16),
	C_TEXT("-",						71), 					C_WAIT(16),
	C_TEXT("  Nurse Hasumi",		72),C_ICON(HASUMI,	3), C_WAIT(64),
	C_WAIT(64),
	C_TEXT("- Plantation -",		73),					C_WAIT(64),
	C_TEXT("The girl Mimiga",		74), 					C_WAIT(16),
	C_TEXT("-",						75), 					C_WAIT(16),
	C_TEXT("  Chie",				76),C_ICON(CHIE,	3), C_WAIT(64),
	C_TEXT("The grandpa Mimiga",	77), 					C_WAIT(16),
	C_TEXT("-",						78), 					C_WAIT(16),
	C_TEXT("  Zett",				79),C_ICON(ZETT,	3), C_WAIT(64),
	C_TEXT("Sprinkler Manager",		80), 					C_WAIT(16),
	C_TEXT("-",						81), 					C_WAIT(16),
	C_TEXT("  Megane",				82),C_ICON(MEGANE,	3), C_WAIT(64),
	C_TEXT("Believes in the",		83), 					C_WAIT(16),
	C_TEXT(" Doctor",				84), 					C_WAIT(16),
	C_TEXT("  The Shovel Brigade",	85),C_ICON(SHOVELBR,3), C_WAIT(64),
	C_WAIT(64),
	// Normal Ending villains/others
	C_FLAG_JUMP(2000, 90),
	C_TEXT("- Villains -",			86),					C_WAIT(64),
	C_TEXT("The power-snatching",	87), 					C_WAIT(16),
	C_TEXT(" betrayer",				88), 					C_WAIT(16),
	C_TEXT("  The Doctor",			89),C_ICON(DOCTOR,	3), C_WAIT(64),
	C_TEXT("The Doctor's servant",	90), 					C_WAIT(16),
	C_TEXT("-",						91), 					C_WAIT(16),
	C_TEXT("  Misery",				92),C_ICON(MISERY,	3), C_WAIT(64),
	C_TEXT("Misery's punching bag",	93), 					C_WAIT(16),
	C_TEXT("-",						94), 					C_WAIT(16),
	C_TEXT("  Balrog",				95),C_ICON(BALROG,	3), C_WAIT(64),
	C_WAIT(64),
	C_TEXT("- Others -",			96),					C_WAIT(64),
	C_TEXT("The Hermit Gunsmith",	97), 					C_WAIT(16),
	C_TEXT("-",						98), 					C_WAIT(16),
	C_TEXT("  Tetsuzou Kamadani",	99),C_ICON(GUNSMITH,3), C_WAIT(64),
	C_TEXT("The mysterious",		100), 					C_WAIT(16),
	C_TEXT(" mushroom",				101), 					C_WAIT(16),
	C_TEXT("  Ma Pignon",			102),C_ICON(MAPIGNON,3),C_WAIT(64),
	C_TEXT("The family living in",	103), 					C_WAIT(16),
	C_TEXT(" the outer wall",		104), 					C_WAIT(16),
	C_TEXT("  The Littles",			105),C_ICON(LITTLES,3), C_WAIT(64),
	C_TEXT("The mysterious",		106), 					C_WAIT(16),
	C_TEXT(" native inhabitants",	107), 					C_WAIT(16),
	C_TEXT("  Cthulhu",				108),C_ICON(CTHULHU,3), C_WAIT(64),
	C_TEXT("The statue carver",		109), 					C_WAIT(16),
	C_TEXT("-",						110), 					C_WAIT(16),
	C_TEXT("  Numahachi",			111),C_ICON(NUMAHCHI,3),C_WAIT(64),
	C_JUMP(100),
	// Best Ending villains/others
	C_LABEL(90),
	C_TEXT("- Villains -",			112),					C_WAIT(64),
	C_TEXT("Entranced by the crown",113), 					C_WAIT(16),
	C_TEXT("-",						114), 					C_WAIT(16),
	C_TEXT("  The Doctor",			115),C_ICON(DOCTOR,	3), C_WAIT(64),
	C_TEXT("Cursed by the crown",	116), 					C_WAIT(16),
	C_TEXT("-",						117), 					C_WAIT(16),
	C_TEXT("  Misery",				118),C_ICON(MISERY,	3), C_WAIT(64),
	C_TEXT("Ultimately a friend",	119), 					C_WAIT(16),
	C_TEXT("-",						120), 					C_WAIT(16),
	C_TEXT("  Balrog",				121),C_ICON(BALROG,	3), C_WAIT(64),
	C_WAIT(64),
	C_TEXT("- Others -",			122),					C_WAIT(64),
	C_TEXT("The Hermit Gunsmith",	123), 					C_WAIT(16),
	C_TEXT("-",						124), 					C_WAIT(16),
	C_TEXT("  Tetsuzou Kamadani",	125),C_ICON(GUNSMITH,3),C_WAIT(64),
	C_TEXT("The memory-restoring",	126), 					C_WAIT(16),
	C_TEXT(" mushroom",				127), 					C_WAIT(16),
	C_TEXT("  Ma Pignon",			128),C_ICON(MAPIGNON,3),C_WAIT(64),
	C_TEXT("The family living in",	129), 					C_WAIT(16),
	C_TEXT(" the outer wall",		130), 					C_WAIT(16),
	C_TEXT("  The Littles",			131),C_ICON(LITTLES,3), C_WAIT(64),
	C_TEXT("The mysterious",		132), 					C_WAIT(16),
	C_TEXT(" native inhabitants",	133), 					C_WAIT(16),
	C_TEXT("  Cthulhu",				134),C_ICON(CTHULHU,3), C_WAIT(64),
	C_TEXT("The statue carver",		135), 					C_WAIT(16),
	C_TEXT("-",						136), 					C_WAIT(16),
	C_TEXT("  Numahachi",			137),C_ICON(NUMAHCHI,3),C_WAIT(64),
	C_WAIT(64),
	C_TEXT("- Bloody Holy Land -",	138),					C_WAIT(64),
	C_TEXT("Jenka's sorrowful",		139), 					C_WAIT(16),
	C_TEXT(" younger brother",		140), 					C_WAIT(16),
	C_TEXT("  Ballos",				141),C_ICON(BALLOS,	3), C_WAIT(64),
	C_LABEL(100),
	// Transition to second part which has short silent cutscenes in various stages
	C_WAIT(144),
	//C_SONG_FADE(),
	//C_WAIT(200),
	C_WAIT(150),
	C_SONG_FADE(),
	C_WAIT(50),
	C_SONG(1),
	C_MOVE(48),
	C_WAIT(50),
	
	C_TEXT(" = Monsters = ", 142),										C_WAIT(32),
	C_WAIT(48),
	C_TEXT(" Leaps and hops: Critter", 143),		C_ICON(CRITTER,	3), C_WAIT(48),
	C_TEXT(" Every cave needs a: Bat", 144),		C_ICON(BAT,		3), C_WAIT(48),
	C_TEXT(" Possessed by something: The Door", 145),C_ICON(THEDOOR,3), C_WAIT(48),
	C_TEXT(" Charges when angered: Behemoth", 146),	C_ICON(BEHEMOTH,3), C_WAIT(48),
	C_TEXT(" White mushroom: Pignon", 147),			C_ICON(PIGNON,	3), C_WAIT(48),
	C_TEXT(" Worth eating: Giant Pignon", 148),		C_ICON(GPIGNON,	3), C_WAIT(48),
	C_TEXT(" There's only one: Chinfish", 149),		C_ICON(CHINFISH,3), C_WAIT(48),
	C_TEXT(" Slices you up: Gravekeeper", 150),		C_ICON(GKEEPER,	3), C_WAIT(48),
	C_TEXT(" Floor-hugging flash: Basil", 151),		C_ICON(BASIL,	3), C_WAIT(48),
	C_TEXT(" A model insect: Beetle", 152),			C_ICON(BEETLE,	3), C_WAIT(48),
	C_TEXT(" The big flyer: Basu", 153),			C_ICON(BASU,	3), C_WAIT(48),
	C_TEXT(" The crusher: Power Critter", 154),		C_ICON(PCRITTER,3), C_WAIT(48),
	C_TEXT(" White mold ghost: Mannan", 155),		C_ICON(MANNAN,	3), C_WAIT(48),
	C_TEXT(" Tiny frog: Puchi", 156),				C_ICON(PUCHI,	3), C_WAIT(48),
	C_TEXT(" Big croaker: Frog", 157),				C_ICON(FROG,	3), C_WAIT(48),
	C_TEXT(" Floats about: Jelly", 158),			C_ICON(JELLY,	3), C_WAIT(48),
	C_TEXT(" Queen Jelly: Kulala", 159),			C_ICON(KULALA,	3), C_WAIT(48),
	C_TEXT(" Violent Mimiga: Rabil", 160),			C_ICON(RAVIL,	3), C_WAIT(48),
	C_TEXT(" Instant deathtrap: Press", 161),		C_ICON(PRESS,	3), C_WAIT(48),
	C_TEXT(" Sudden chomper: Sandcroc", 162),		C_ICON(SANDCROC,3), C_WAIT(48),
	C_TEXT(" Wandering skull: Skullhead", 163),		C_ICON(SKULHEAD,3), C_WAIT(48),
	C_TEXT(" Sand runner: Skullstep", 164),			C_ICON(SKULSTEP,3), C_WAIT(48),
	C_TEXT(" White for: Skeleton", 165),			C_ICON(SKELETON,3), C_WAIT(48),
	C_TEXT(" Sand Zone Hunter: Crow", 166),			C_ICON(CROW,	3), C_WAIT(48),
	C_TEXT(" Tough missile: Armadillo", 167),		C_ICON(ARMADILL,3), C_WAIT(48),
	C_TEXT(" From one, many: Polish", 168),			C_ICON(POLISH,	3), C_WAIT(48),
	C_TEXT(" Scattering everywhere: Baby", 169),	C_ICON(BABY,	3), C_WAIT(48),
	C_TEXT(" From Frenzied Toroko: Flower", 170),	C_ICON(FLOWER,	3), C_WAIT(48),
	C_TEXT(" Labyrinth dweller: Gaudi", 171),		C_ICON(GAUDI,	3), C_WAIT(48),
	C_TEXT(" Labyrinth warrior: Armor", 172),		C_ICON(ARMOR,	3), C_WAIT(48),
	C_TEXT(" Labyrinth baby: Gaudi Egg", 173),		C_ICON(GAUDIEGG,3), C_WAIT(48),
	C_TEXT(" Fiery fan: Fire Whirr", 174),			C_ICON(FIREWHIR,3), C_WAIT(48),
	C_TEXT(" Unknown organism: Buyobuyo Base", 175),C_ICON(BUYOBASE,3), C_WAIT(48),
	C_TEXT(" And: Buyobuyo", 176),					C_ICON(BUYO,	3), C_WAIT(48),
	C_TEXT(" Gaudi spirit: Fuzz", 177),				C_ICON(FUZZ,	3), C_WAIT(48),
	C_TEXT(" Spirit clump: Fuzz Core", 178),		C_ICON(FUZZCORE,3), C_WAIT(48),
	C_TEXT(" An old friend: Porcupine Fish", 179),	C_ICON(BLOWFISH,3), C_WAIT(48),
	C_TEXT(" Hatching failure: Dragon Zombie", 180),C_ICON(DRAGONZ,	3), C_WAIT(48),
	C_TEXT(" Timed explosive: Counter Bomb", 181),	C_ICON(CNTRBOMB,3), C_WAIT(48),
	C_TEXT(" Outside flutterer: Night Spirit", 182),C_ICON(NIGHTSPR,3), C_WAIT(48),
	C_TEXT(" Jumps: Hoppy", 183),					C_ICON(HOPPY,	3), C_WAIT(48),
	C_TEXT(" Photosynthetic warrior: Midorin", 184),C_ICON(MIDORIN,	3), C_WAIT(48),
	C_TEXT(" Born of earth: Droll", 185),			C_ICON(DROLL,	3), C_WAIT(48),
	C_TEXT(" Stepping stone: Gunfish", 186),		C_ICON(GUNFISH,	3), C_WAIT(48),
	C_TEXT(" Mother bat: Orangebell", 187),			C_ICON(ORANGEBL,3), C_WAIT(48),
	C_TEXT(" Plantation dragonfly: Stumpy", 188),	C_ICON(STUMPY,	3), C_WAIT(48),
	// Best end only
	C_FLAG_JUMP(2000, 190), C_JUMP(200), C_LABEL(190),
	//C_WAIT(2), // Leaving this out, it messes up the alignment
	C_TEXT(" Hell's messenger: Bute", 189),			C_ICON(BUTE,	3), C_WAIT(48),
	C_TEXT(" Hell's messenger: Mesa", 190),			C_ICON(MESA,	3), C_WAIT(48),
	C_TEXT(" Innocent demon: Green Devil", 191),	C_ICON(GRNDEVIL,3), C_WAIT(48),
	C_TEXT(" Rolls along the walls: Rolling", 192),	C_ICON(ROLLING,	3), C_WAIT(48),
	C_TEXT(" Blocks passages: Deleet", 193),		C_ICON(DELEET,	3), C_WAIT(48),
	C_LABEL(200),
	
	C_WAIT(80),
	C_TEXT("= Bosses =", 194),								C_WAIT(32),
	C_WAIT(48),
	C_TEXT("Frenzied Mimiga that", 195), 					C_WAIT(16),
	C_TEXT(" kidnapped Sue", 196),							C_WAIT(16),
	C_TEXT("  Igor", 197),				C_ICON(IGOR,	3), C_WAIT(64),
	C_TEXT("Misery transformed", 198), 						C_WAIT(16),
	C_TEXT(" Balrog into", 199),							C_WAIT(16),
	C_TEXT("  Balfrog", 200),			C_ICON(BALFROG,	3), C_WAIT(64),
	C_TEXT("Machine-monster that", 201), 					C_WAIT(16),
	C_TEXT(" lurks in the sand", 202),						C_WAIT(16),
	C_TEXT("  Omega", 203),				C_ICON(OMEGA,	3), C_WAIT(64),
	C_TEXT("Dosed with red flowers", 204), 					C_WAIT(16),
	C_TEXT("-", 205), 										C_WAIT(16),
	C_TEXT("  Toroko +", 206),			C_ICON(TOROKOF,	3), C_WAIT(64),
	C_TEXT("Ghost that invaded", 207), 						C_WAIT(16),
	C_TEXT(" the clinic", 208),								C_WAIT(16),
	C_TEXT("  Pooh Black", 209),		C_ICON(POOHBLK,	3), C_WAIT(64),
	C_TEXT("Big boss of the", 210), 						C_WAIT(16),
	C_TEXT(" labyrinth", 211),								C_WAIT(16),
	C_TEXT("  Monster X", 212),			C_ICON(MONSTERX,3), C_WAIT(64),
	C_TEXT("Heart of the island", 213), 					C_WAIT(16),
	C_TEXT("-", 214), 										C_WAIT(16),
	C_TEXT("  Core", 215),				C_ICON(CORE,	3), C_WAIT(64),
	C_TEXT("Big fish in the", 216), 						C_WAIT(16),
	C_TEXT(" island's artery", 217),						C_WAIT(16),
	C_TEXT("  Ironhead", 218),			C_ICON(IRONHEAD,3), C_WAIT(64),
	C_TEXT("Twin dragon surprise", 219), 					C_WAIT(16),
	C_TEXT(" attackers", 220),								C_WAIT(16),
	C_TEXT("  Sisters", 221),			C_ICON(SISTERS,	3), C_WAIT(64),
	C_TEXT("True heroes meet the", 222), 					C_WAIT(16),
	C_TEXT("-", 223), 										C_WAIT(16),
	C_TEXT("  Red Demon", 224),			C_ICON(REDDEMON,3), C_WAIT(64),
	C_TEXT("The red crystal", 225), 						C_WAIT(16),
	C_TEXT(" runs wild", 226),								C_WAIT(16),
	C_TEXT("  Muscle Doctor", 227),		C_ICON(DOCTORF,	3), C_WAIT(64),
	C_TEXT("The Doctor and the", 228), 						C_WAIT(16),
	C_TEXT(" island's heart", 229),							C_WAIT(16),
	C_TEXT("  Undead Core", 230),		C_ICON(UNDCORE,	3), C_WAIT(64),
	// Best end only
	C_FLAG_JUMP(2000, 290), C_JUMP(300), C_LABEL(290),
	//C_WAIT(2),
	C_TEXT("The swollen mech", 231), 						C_WAIT(16),
	C_TEXT("-", 232), 										C_WAIT(16),
	C_TEXT("  Heavy Press", 233),		C_ICON(HVPRESS,	3), C_WAIT(64),
	C_TEXT("Hate and madness", 234), 						C_WAIT(16),
	C_TEXT(" given flesh", 235),							C_WAIT(16),
	C_TEXT("  Ballos", 236),			C_ICON(BALLOS2,	3), C_WAIT(64),
	C_LABEL(300),
	
	C_WAIT(80),
	C_MOVE(32),
	C_TEXT(" = BGM = ", 237),								C_WAIT(32),
	C_WAIT(32),
	C_TEXT("Access", 238),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Gestation", 239),			C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Mimiga Village", 240),		C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Plant", 241),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Balrog's Theme", 242),		C_ICON(MUSIC,	3), C_WAIT(32),
	C_WAIT(32),
	C_TEXT("Gravity", 243),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Cemetery", 244),			C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Safety", 245),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Mischievous Robot", 246),	C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Pulse", 247),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_WAIT(32),
	C_TEXT("On to Grasstown", 248),		C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Eyes of Flame", 249),		C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Meltdown 2", 250),			C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Tyrant", 251),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Run!", 252),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_WAIT(32),
	C_TEXT("Jenka 1", 253),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Jenka 2", 254),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Labyrinth Fight", 255),		C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Geothermal", 256),			C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Oppression", 257),			C_ICON(MUSIC,	3), C_WAIT(32),
	C_WAIT(32),
	C_TEXT("Living Waterway", 258),		C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Quiet", 259),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Scorching Back", 260),		C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Moonsong", 261),			C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Hero's End", 262),			C_ICON(MUSIC,	3), C_WAIT(32),
	C_WAIT(32),
	C_TEXT("Cave Story", 263),			C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Last Cave", 264),			C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Balcony", 265),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Charge", 266),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Zombie", 267),				C_ICON(MUSIC,	3), C_WAIT(32),
	C_WAIT(32),
	C_TEXT("Last Battle", 268),			C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Break Down", 269),			C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Running Hell", 270),		C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("Seal Chamber", 271),		C_ICON(MUSIC,	3), C_WAIT(32),
	C_TEXT("The Way Back Home", 272),	C_ICON(MUSIC,	3), C_WAIT(32),
	
	C_WAIT(96),
	C_TEXT("= Special Thanks =", 273),						C_WAIT(32),
	C_MOVE(32),
	C_WAIT(32),
	C_TEXT("Torai", 274),				C_ICON(DEBUGCAT,3), C_WAIT(48),
	C_TEXT("Naoku", 275),				C_ICON(SWORD,	3), C_WAIT(48),
	C_TEXT("Kuroihito", 276),			C_ICON(KUROI,	3), C_WAIT(48),
	C_TEXT("BA2", 277),					C_ICON(BA2,		3), C_WAIT(48),
	C_TEXT("Okami", 278),				C_ICON(OKAMI,	3), C_WAIT(48),
	C_TEXT("Nao", 279),					C_ICON(NAO,		3), C_WAIT(48),
	// Two for translation
	C_TEXT("Shih Tzu", 280),			C_ICON(PUPPY,	3), C_WAIT(48),
	C_TEXT("Gideon Zhi", 281),			C_ICON(GIDEON,	3), C_WAIT(48),
	
	C_TEXT("And many others", 282),							C_WAIT(48),

	// MD staff roll
	C_WAIT(96),
	C_TEXT("= Mega Drive Version =", 283),                  C_WAIT(32),
    C_MOVE(32),
    C_WAIT(32),
    C_TEXT("Developed by", 284),							C_WAIT(16),
	C_TEXT("-", 285),										C_WAIT(16),
	C_TEXT("  GND / andwn", 286),							C_WAIT(64),
	C_TEXT("Free QA and other", 287),						C_WAIT(16),
	C_TEXT(" human sacrifices", 288),						C_WAIT(16),
	C_TEXT("  Andwhy", 289),								C_WAIT(48),
	C_TEXT("  Sik", 290),									C_WAIT(48),
	C_TEXT("  MOF", 291),									C_WAIT(64),
	C_TEXT("  ...and you?", 292),							C_WAIT(96),

	C_LOADPXE(),
	C_WAIT(64),
	C_TEXT("Thank you very much.", 299),C_ICON(THANKS,	3), C_WAIT(32),
	C_WAIT(232),
	//C_WAIT(128),
	C_MOVE(80),
	C_TEXT("Cave Story ~ The End", 300),
	C_WAIT(264),
	C_END()
};

const illustration_info_def illustration_info[20] = {
	{ NULL,                          0,   NULL,                  NULL       },
	{ (const uint32_t*) PAT_Ill01, 411, (const uint16_t*) MAP_Ill01, PAL_Ill01 },
	{ (const uint32_t*) PAT_Ill02, 411, (const uint16_t*) MAP_Ill02, PAL_Ill02 },
	{ (const uint32_t*) PAT_Ill03, 411, (const uint16_t*) MAP_Ill03, PAL_Ill03 },
	{ (const uint32_t*) PAT_Ill04, 411, (const uint16_t*) MAP_Ill04, PAL_Ill04 },
	{ (const uint32_t*) PAT_Ill05, 411, (const uint16_t*) MAP_Ill05, PAL_Ill05 },
	{ (const uint32_t*) PAT_Ill06, 411, (const uint16_t*) MAP_Ill06, PAL_Ill06 },
	{ (const uint32_t*) PAT_Ill07, 411, (const uint16_t*) MAP_Ill07, PAL_Ill07 },
	{ (const uint32_t*) PAT_Ill08, 411, (const uint16_t*) MAP_Ill08, PAL_Ill08 },
	{ (const uint32_t*) PAT_Ill09, 411, (const uint16_t*) MAP_Ill09, PAL_Ill09 },
	{ (const uint32_t*) PAT_Ill10, 411, (const uint16_t*) MAP_Ill10, PAL_Ill10 },
	{ (const uint32_t*) PAT_Ill11, 411, (const uint16_t*) MAP_Ill11, PAL_Ill11 },
	{ (const uint32_t*) PAT_Ill12, 411, (const uint16_t*) MAP_Ill12, PAL_Ill12 },
	{ NULL,                          0,   NULL,                  NULL       },
	{ (const uint32_t*) PAT_Ill14, 411, (const uint16_t*) MAP_Ill14, PAL_Ill14 },
	{ (const uint32_t*) PAT_Ill15, 411, (const uint16_t*) MAP_Ill15, PAL_Ill15 },
	{ (const uint32_t*) PAT_Ill16, 411, (const uint16_t*) MAP_Ill16, PAL_Ill16 },
	{ (const uint32_t*) PAT_Ill17, 411, (const uint16_t*) MAP_Ill17, PAL_Ill17 },
	{ (const uint32_t*) PAT_Ill18, 411, (const uint16_t*) MAP_Ill18, PAL_Ill18 },
	{ NULL,                          0,   NULL,                  NULL       },
};
