#include "tables.h"

#include "ai.h"
#include "resources.h"
#include "sheet.h"

const npc_info_def npc_info[NPC_COUNT + 9 + 3] = {
	{ NULL, 		NOSHEET, PAL0, 		0, "Nothing",
		&onspawn_op2snap, NULL, NULL },
	{ NULL, 		SHEET_ENERGY, PAL1, 1, "Weapon Energy",
		&onspawn_energy, &ai_energy, NULL },
	{ &SPR_Behem, 	NOSHEET, PAL1, 		1, "Behemoth",
		NULL, &ai_behemoth, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 		0, "Nothing",
		NULL, NULL, NULL },
	{ NULL, 		NOSHEET, PAL0, 		0, "Nothing",
		NULL, NULL, NULL },
	{ NULL, 		NOSHEET, PAL3, 		1, "Green Critter",
		&onspawn_snap, &ai_critter, &ondeath_default },
	{ NULL, 		SHEET_BEETLE, PAL3, 1, "Green Beetle",
		NULL, &ai_beetle, &ondeath_default },
	{ &SPR_Basil, 	NOSHEET, PAL1, 		1, "Basil",
		&onspawn_basil, &ai_basil, NULL },
	{ NULL, 		SHEET_BEETLE, PAL3, 1, "Green Beetle (Follow)",
		&onspawn_beetleFollow, &ai_beetleFollow, &ondeath_default },
	{ &SPR_Balrog, 	NOSHEET, PAL1, 		2, "Balrog (Drops in)",
		&onspawn_balrog, &ai_balrog_drop_in, NULL },
	{ NULL, 		NOSHEET, PAL0, 		0, "Nothing",
		NULL, NULL, NULL },
	{ &SPR_EnergyShot, NOSHEET, PAL1, 	1, "Igor Projectile",
		NULL, &ai_genericproj, NULL },
	{ &SPR_Balrog, 	NOSHEET, PAL1, 		2, "Balrog (Scene)",
		&onspawn_balrog, &ai_balrog, NULL },
	{ &SPR_ForceField, NOSHEET, PAL1, 	1, "Force Field",
		NULL, NULL, NULL },
	{ &SPR_Key, 	NOSHEET, PAL1, 		1, "Santa's Key",
		NULL, NULL, NULL },
	{ &SPR_Chest, 	NOSHEET, PAL1, 		1, "Treasure Chest",
		NULL, &ai_grav, NULL },
	/* 0x010 (16) */
	{ &SPR_Save, 	NOSHEET, PAL1, 		1, "Save Point",
		NULL, &ai_savepoint, NULL },
	{ &SPR_Refill, 	NOSHEET, PAL1, 		1, "Health & Ammo Refill",
		NULL, &ai_refill, NULL },
	{ &SPR_Door, 	NOSHEET, PAL1, 		1, "Door",
		&onspawn_door, &ai_door, NULL },
	{ &SPR_Balrog, 	NOSHEET, PAL1, 		2, "Balrog (Busts in)",
		&onspawn_balrog, &ai_balrog_bust_in, NULL },
	{ &SPR_Computer, NOSHEET, PAL1, 	1, "Computer",
		NULL, &ai_computer, NULL },
	{ &SPR_Chest2, 	NOSHEET, PAL1, 		1, "Opened Chest",
		&onspawn_snap, NULL, NULL },
	{ &SPR_Tele, 	NOSHEET, PAL1, 		1, "Teleporter",
		NULL, NULL, NULL },
	{ &SPR_TeleLight, NOSHEET, PAL1, 	1, "Teleporter Lights",
		&onspawn_teleLight, &ai_teleLight, NULL },
	{ &SPR_CritBig, NOSHEET, PAL0, 		1, "Power Critter",
		&onspawn_snap, &ai_critter, &ondeath_default },
	{ &SPR_Platform, NOSHEET, PAL1, 	1, "Lift Platform",
		&onspawn_lift, &ai_lift, NULL },
	{ NULL, 		SHEET_BAT, PAL0, 	1, "Bat (Circling)",
		NULL, &ai_batCircle, &ondeath_default },
	{ &SPR_Trap, 	NOSHEET, PAL1, 		1, "Death Trap",
		NULL, NULL, NULL },
	{ NULL, 		SHEET_CRITTER, PAL3, 1, "Flying Critter",
		&onspawn_snap, &ai_critter, &ondeath_default },
	{ &SPR_Cthu, 	NOSHEET, PAL3, 		1, "Cthulhu",
		NULL, NULL, NULL },
	{ &SPR_Gunsmith, NOSHEET, PAL3, 	1, "Hermit Gunsmith",
		&onspawn_snap, NULL, NULL },
	{ NULL, 	SHEET_BAT, PAL0, 1, "Bat (Hanging)",
		&onspawn_batHang, &ai_batHang, &ondeath_default },
	/* 0x020 (32) */
	{ &SPR_LifeUp, 	NOSHEET, PAL1, 1, "Life Capsule",
		NULL, NULL, NULL },
	{ &SPR_EnergyShot, NOSHEET, PAL1, 1, "Balrog Energy Bounce",
		NULL, &ai_balrogShot, NULL },
	{ &SPR_Bed, 	NOSHEET, PAL1, 1, "Bed",
		NULL, NULL, NULL },
	{ &SPR_Mannan, 	NOSHEET, PAL3, 1, "Mannan",
		NULL, &ai_mannan, NULL },
	{ &SPR_Balrog, 	NOSHEET, PAL1, 2, "Balrog (Second Fight)",
		&onspawn_balrog, &ondeath_balrogFlying, &ai_balrogFlying },
	{ &SPR_Sign, 	NOSHEET, PAL1, 1, "Sign Post",
		NULL, NULL, NULL },
	{ &SPR_Fire, 	NOSHEET, PAL1, 1, "Fireplace Fire",
		NULL, NULL, NULL },
	{ &SPR_SaveSign, NOSHEET, PAL1, 1, "Save Sign",
		&onspawn_op2anim, NULL, NULL },
	{ &SPR_Santa, 	NOSHEET, PAL3, 1, "Santa",
		NULL, &ai_santa, NULL },
	{ NULL, 		NOSHEET, PAL0, 0, "Busted Doorway",
		&onspawn_door, NULL, NULL },
	{ &SPR_Sue, 	NOSHEET, PAL3, 1, "Sue",
		&onspawn_snapflip, &ai_sue, NULL },
	{ &SPR_Board, 	NOSHEET, PAL1, 2, "Blackboard",
		&onspawn_blackboard, NULL, NULL },
	{ &SPR_Polish, 	NOSHEET, PAL3, 1, "Polish",
		NULL, &ai_polish, &ondeath_default },
	{ &SPR_Baby, 	NOSHEET, PAL3, 1, "Baby",
		NULL, &ai_baby, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 0, "Horiz/Vert Trigger",
		NULL, &ai_trigger, NULL },
	{ &SPR_Sandcroc, NOSHEET, PAL3, 2, "Green Sandcroc",
		NULL, &ai_sandcroc, &ondeath_default },
	/* 0x030 (48) */
	{ NULL, 		NOSHEET, PAL0, 1, "Omega Projectile",
		NULL, NULL, NULL },
	{ &SPR_Skullhead, NOSHEET, PAL1, 1, "Skullhead",
		NULL, &ai_skullhead, &ondeath_default },
	{ &SPR_Skullhead, NOSHEET, PAL1, 1, "Skeleton",
		NULL, &ai_skullhead, &ondeath_default },
	{ &SPR_Crow, 	NOSHEET, PAL3, 1, "Crow & Skullhead",
		NULL, &ai_crow, &ondeath_default },
	{ &SPR_Robot, 	NOSHEET, PAL3, 1, "Blue Robot (Sitting)",
		NULL, NULL, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, NULL },
	{ &SPR_Skullhead, NOSHEET, PAL1, 1, "Skullstep",
		NULL, &ai_skullhead, &ondeath_default },
	{ &SPR_Kazuma, 	NOSHEET, PAL3, 1, "Kazuma",
		&onspawn_snap, &ai_kazuma, NULL },
	{ &SPR_BtlHB, 	SHEET_BEETLE, PAL3, 1, "Brown Beetle",
		NULL, &ai_beetle, &ondeath_default },
	{ &SPR_Crow, 	SHEET_CROW, PAL3, 1, "Crow",
		NULL, &ai_crow, &ondeath_default },
	{ &SPR_Basu, 	NOSHEET, PAL3, 1, "Basu",
		&onspawn_basu, &ai_basu, &ondeath_default },
	{ &SPR_DoorE, 	NOSHEET, PAL1, 1, "Door Enemy",
		NULL, &ai_theDoor, &ondeath_default },
	{ &SPR_Toroko, 	NOSHEET, PAL3, 1, "Toroko",
		&onspawn_op2flip, &ai_toroko, NULL },
	{ &SPR_King, 	NOSHEET, PAL3, 1, "King",
		&onspawn_op2flip, &ai_king, NULL },
	{ &SPR_KazuCom, NOSHEET, PAL3, 1, "Kazuma (Computer)",
		&onspawn_snap, &ai_npc_at_computer, NULL },
	{ &SPR_Toroko, 	NOSHEET, PAL3, 1, "Toroko (Attacking)",
		&onspawn_torokoAtk, &ai_torokoAtk, NULL },
	/* 0x040 (64) */
	{ NULL, 		SHEET_CRITTER, PAL2, 1, "Blue Hopping Critter",
		&onspawn_snap, &ai_critter, &ondeath_default },
	{ NULL, 	SHEET_BAT, PAL0, 1, "Bat",
		&onspawn_batVertical, &ai_batVertical, &ondeath_default },
	{ &SPR_Bubble, 	NOSHEET, PAL0, 1, "Misery's Bubble",
		NULL, &ai_misery_bubble, NULL },
	{ &SPR_Misery, 	NOSHEET, PAL0, 1, "Misery (Floating)",
		NULL, &ai_misery_float, NULL },
	{ &SPR_Balrog, 	NOSHEET, PAL1, 2, "Balrog (First Fight)",
		&onspawn_balrog, &ai_balrogRunning, &ondeath_balrogRunning },
	{ &SPR_Pignon, 	SHEET_PIGNON, PAL1, 1, "Pignon",
		NULL, &ai_pignon, &ondeath_default },
	{ &SPR_Sparkle, NOSHEET, PAL1, 1, "Sparkling Item",
		NULL, NULL, NULL },
	{ &SPR_Fish, 	NOSHEET, PAL0, 1, "Chinfish",
		NULL, NULL, &ondeath_default },
	{ &SPR_Sprinkler, NOSHEET, PAL1, 1, "Sprinkler",
		NULL, NULL, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "Water Drop",
		NULL, NULL, NULL },
	{ &SPR_Jack, 	NOSHEET, PAL3, 1, "Jack",
		&onspawn_snap, &ai_jack, NULL },
	{ &SPR_Kanpachi, NOSHEET, PAL3, 1, "Kanpachi (Fishing)",
		NULL, &ai_kanpachi_fishing, NULL },
	{ &SPR_Flower, 	NOSHEET, PAL3, 1, "Flowers",
		&onspawn_flower, NULL, NULL },
	{ &SPR_Sanda, 	NOSHEET, PAL3, 2, "Sandame's Pavilion",
		NULL, NULL, NULL },
	{ &SPR_Pot, 	NOSHEET, PAL1 , 1, "Pot",
		&onspawn_op2anim, NULL, NULL },
	{ &SPR_Mahin, 	NOSHEET, PAL3, 1, "Mahin",
		&onspawn_snap, NULL, NULL },
	/* 0x050 (80) */
	{ &SPR_Keeper, 	NOSHEET, PAL1, 1, "Gravekeeper",
		&onspawn_gkeeper, &ai_gkeeper, &ondeath_default },
	{ &SPR_PignonB, NOSHEET, PAL1, 1, "Big Pignon",
		NULL, &ai_pignon, &ondeath_default },
	{ &SPR_Misery, 	NOSHEET, PAL0, 1, "Misery (Standing)",
		NULL, NULL, NULL },
	{ &SPR_Igor, 	NOSHEET, PAL3, 4, "Igor (Scene)",
		&onspawn_igor, &ai_igorscene, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "Basu Projectile",
		NULL, NULL, NULL },
	{ &SPR_Term, 	NOSHEET, PAL1, 1, "Terminal",
		NULL, &ai_terminal, NULL },
	{ NULL, 	SHEET_MISSILE, PAL1, 1, "Missile",
		&onspawn_op2anim, &ai_missile, NULL },
	{ NULL, 	SHEET_HEART, PAL1, 1, "Heart",
		&onspawn_op2anim, &ai_heart, NULL },
	{ &SPR_Igor, 	NOSHEET, PAL3, 4, "Igor (Boss)",
		&onspawn_igor, &ai_igor, &ondeath_igor },
	{ &SPR_Igor, 	NOSHEET, PAL3, 4, "Igor (Defeated)",
		&onspawn_igor, &ai_igordead, NULL },
	{ NULL, 		NOSHEET, PAL0, 0, "Nothing",
		NULL, NULL, NULL },
	{ &SPR_Cage, 	NOSHEET, PAL1, 1, "Cage",
		&onspawn_snap, NULL, NULL },
	{ &SPR_SueCom, 	NOSHEET, PAL3, 1, "Sue (Computer)",
		&onspawn_snap, &ai_npc_at_computer, NULL },
	{ &SPR_Chaco, 		NOSHEET, PAL3, 1, "Chaco",
		NULL, &ai_chaco, NULL },
	{ &SPR_Kulala, 	NOSHEET, PAL0, 2, "Kulala",
		NULL, NULL, &ondeath_default },
	{ NULL,		 	SHEET_JELLY, PAL0, 1, "Jelly",
		NULL, &ai_jelly, &ondeath_default },
	/* 0x060 (96) */
	{ &SPR_Fan, 	NOSHEET, PAL1, 1, "Fan (Left)",
		&onspawn_fan, &ai_fan, NULL },
	{ &SPR_Fan, 	NOSHEET, PAL1, 1, "Fan (Up)",
		&onspawn_fan, &ai_fan, NULL },
	{ &SPR_Fan, 	NOSHEET, PAL1, 1, "Fan (Right)",
		&onspawn_fan, &ai_fan, NULL },
	{ &SPR_Fan, 	NOSHEET, PAL1, 1, "Fan (Down)",
		&onspawn_fan, &ai_fan, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "Grate",
		NULL, NULL, NULL },
	{ &SPR_PowerScreen, NOSHEET, PAL1, 1, "Power Controls (Screen)",
		NULL, NULL, NULL },
	{ &SPR_Wave, 	NOSHEET, PAL1, 1, "Power Controls (Flow)",
		&onspawn_powerc, NULL, NULL },
	{ &SPR_ManShot, NOSHEET, PAL1, 1, "Mannan Projectile",
		NULL, &ai_mannanShot, NULL },
	{ &SPR_Frog, 	NOSHEET, PAL3, 1, "Frog",
		NULL, &ai_frog, &ondeath_default },
	{ &SPR_Hey, 	NOSHEET, PAL1, 1, "Hey!",
		NULL, &ai_hey, NULL },
	{ &SPR_Hey, 	NOSHEET, PAL1, 1, "Hey! (Emitter)",
		NULL, &ai_hey, NULL },
	{ &SPR_Malco, 	NOSHEET, PAL1, 1, "Malco",
		NULL, &ai_malco, NULL },
	{ &SPR_FrogShot, NOSHEET, PAL1, 1, "Balfrog Projectile",
		&onspawn_persistent, &ai_genericproj, NULL },
	{ &SPR_Malco, 	NOSHEET, PAL1, 1, "Malco (Damaged)",
		&onspawn_malcoBroken, NULL, NULL },
	{ &SPR_FrogSm, 	NOSHEET, PAL3, 1, "Puchi",
		NULL, &ai_frog, &ondeath_default },
	{ &SPR_Quotele, NOSHEET, PAL0, 1, "Quote Teleporting Out",
		&onspawn_teleOut, &ai_teleOut, NULL },
	/* 0x070 (112) */
	{ &SPR_Quotele, NOSHEET, PAL0, 1, "Quote Teleporting In",
		&onspawn_teleIn, &ai_teleIn, NULL },
	{ &SPR_Booster, NOSHEET, PAL3, 1, "Prof. Booster",
		NULL, &ai_booster, NULL },
	{ &SPR_Press, 	NOSHEET, PAL1, 1, "Press",
		NULL, &ai_press, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 2, "Ravil",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Flower Petals",
		NULL, NULL, NULL },
	{ &SPR_Curly, 	NOSHEET, PAL3, 1, "Curly",
		&onspawn_snap, &ai_curly, NULL },
	{ &SPR_CurlyB, 	NOSHEET, PAL3, 1, "Curly (Boss)",
		&onspawn_snap, &ai_curlyBoss, &ondeath_curlyBoss },
	{ &SPR_Table, 	NOSHEET, PAL1, 1, "Tables & Chair",
		NULL, NULL, NULL },
	{ &SPR_CurlyMimi, NOSHEET, PAL3, 1, "Bar Mimiga 1",
		NULL, &ai_curlys_mimigas, &ondeath_default },
	{ &SPR_CurlyMimi, NOSHEET, PAL3, 1, "Bar Mimiga 2",
		NULL, &ai_curlys_mimigas, &ondeath_default },
	{ &SPR_CurlyMimi, NOSHEET, PAL3, 1, "Bar Mimiga (Enemy)",
		NULL, &ai_curlys_mimigas, &ondeath_default },
	{ &SPR_MGunB1, 	NOSHEET, PAL0, 1, "Curly Projectile",
		&onspawn_persistent, &ai_curlyBossShot, NULL },
	{ &SPR_Sunstone, NOSHEET, PAL2, 1, "Sunstone",
		&onspawn_sunstone, &ai_sunstone, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "Hidden Powerup",
		&onspawn_hiddenPowerup, &ai_hiddenPowerup, NULL },
	{ &SPR_Puppy, 	NOSHEET, PAL1, 1, "Puppy (Runs Away)",
		&onspawn_puppy, NULL, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, NULL },
	/* 0x080 (128) */
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, NULL },
	{ &SPR_Puppy, 	NOSHEET, PAL1, 1, "Puppy (Tail Wag)",
		&onspawn_puppy, NULL, NULL },
	{ &SPR_Puppy, 	NOSHEET, PAL1, 1, "Puppy (Sleeping)",
		&onspawn_puppy, NULL, NULL },
	{ &SPR_Puppy, 	NOSHEET, PAL1, 1, "Puppy (Bark)",
		&onspawn_puppy, NULL, NULL },
	{ &SPR_Jenka, 	NOSHEET, PAL3, 1, "Jenka",
		NULL, &ai_jenka, NULL },
	{ &SPR_Armadl, 	NOSHEET, PAL3, 1, "Armadillo",
		NULL, &ai_armadillo, &ondeath_default },
	{ &SPR_Skullhead, NOSHEET, PAL3, 1, "Skeleton",
		NULL, &ai_skullhead, &ondeath_default },
	{ &SPR_Puppy, 	NOSHEET, PAL1, 1, "Puppy (Carried)",
		&onspawn_puppyCarry, &ai_puppyCarry, NULL },
	{ &SPR_BigDoorFrame, NOSHEET, PAL1, 2, "Large Doorway (Frame)",
		NULL, NULL, NULL },
	{ &SPR_BigDoor, NOSHEET, PAL1, 1, "Large Doorway (Doors)",
		&onspawn_doorway, &ai_doorway, NULL },
	{ &SPR_Doctor, 	NOSHEET, PAL3, 1, "Doctor (Crowned)",
		&onspawn_snap, &ai_doctor, NULL },
	{ &SPR_ToroBoss, NOSHEET, PAL3, 2, "Frenzied Toroko",
		&onspawn_torokoBoss, &ai_torokoBoss, &ondeath_torokoBoss },
	{ &SPR_ToroBlock, NOSHEET, PAL1, 1, "Block",
		&onspawn_persistent, &ai_torokoBlock, NULL },
	{ &SPR_ToroFlower, NOSHEET, PAL3, 1, "Flowercub",
		&onspawn_persistent, &ai_torokoFlower, &ondeath_default },
	{ &SPR_Jenka, 	NOSHEET, PAL3, 1, "Jenka (Collapsed)",
		&onspawn_jenka, NULL, NULL },
	/* 0x090 (144) */
	{ &SPR_Toroko, 	NOSHEET, PAL3, 1, "Toroko (Teleport In)",
		NULL, &ai_toroko_teleport_in, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, NULL },
	{ NULL, 		NOSHEET, PAL0, 4, "Lightning",
		NULL, NULL, NULL },
	{ NULL, 		NOSHEET, PAL2, 1, "Purple Critter",
		&onspawn_snap, &ai_critter, &ondeath_default },
	{ &SPR_LabShot, NOSHEET, PAL2, 1, "Critter Projectile",
		&onspawn_persistent, NULL, NULL },
	{ &SPR_MazeBlock, NOSHEET, PAL2, 1, "Moving Block (Horiz)",
		&onspawn_block, &ai_blockh, NULL },
	{ &SPR_Quote, 	NOSHEET, PAL0, 1, "Quote",
		&onspawn_persistent, &ondeath_player, &ai_player },
	{ &SPR_Robot, 	NOSHEET, PAL3, 1, "Blue Robot",
		NULL, &ai_blue_robot, NULL },
	{ NULL, 		NOSHEET, PAL2, 1, "Shutter (Stuck)",
		NULL, &ai_shutter_stuck, &ondeath_default },
	{ &SPR_Gaudi, NOSHEET, PAL2, 1, "Gaudi",
		NULL, &ai_gaudi, &ondeath_default },
	{ &SPR_Gaudi, NOSHEET, PAL2, 1, "Gaudi (Defeated)",
		NULL, &ai_gaudiDying, &ondeath_default },
	{ &SPR_Gaudi, NOSHEET, PAL2, 1, "Gaudi (Flying)",
		NULL, &ai_gaudiFlying, &ondeath_default },
	{ &SPR_LabShot, NOSHEET, PAL2, 1, "Gaudi Projectile",
		&onspawn_persistent, &ai_gaudiArmoredShot, NULL },
	{ &SPR_MazeBlock, NOSHEET, PAL2, 1, "Moving Block (Vert)",
		&onspawn_block, &ai_blockv, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "Monster X Projectile",
		NULL, NULL, NULL },
	{ NULL, 		NOSHEET, PAL0, 4, "Monster X (Defeated)",
		NULL, NULL, NULL },
	/* 0x0A0 (160) */
	{ &SPR_Dark, 	NOSHEET, PAL3, 2, "Pooh Black",
		NULL, &ai_pooh_black, &ondeath_default },
	{ &SPR_DarkBub, NOSHEET, PAL3, 1, "Pooh Black Projectile",
		NULL, &ai_pooh_black_bubble, NULL },
	{ &SPR_Dark, 	NOSHEET, PAL3, 2, "Pooh Black (Defeated)",
		NULL, &ai_pooh_black_dying, NULL },
	{ &SPR_DrGero, 	NOSHEET, PAL3, 1, "Dr. Gero",
		NULL, &generic_npc_states, NULL },
	{ &SPR_Nurse, 	NOSHEET, PAL3, 1, "Nurse Hasumi",
		NULL, &generic_npc_states, NULL },
	{ &SPR_Curly, 	NOSHEET, PAL3, 1, "Curly (Collapsed)",
		NULL, &ai_curly, NULL },
	{ &SPR_GaudiMerch, NOSHEET, PAL3, 1, "Chaba",
		NULL, NULL, NULL },
	{ &SPR_Booster, NOSHEET, PAL3, 1, "Prof. Booster (Fall)",
		&onspawn_persistent, &ai_booster_falling, NULL },
	{ &SPR_Boulder, NOSHEET, PAL3, 4, "Boulder",
		NULL, &ai_boulder, NULL },
	{ &SPR_Balrog, 	NOSHEET, PAL1, 2, "Balrog (Third Fight)",
		&onspawn_balrog, &ai_balrog_boss_missiles, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Balrog Missile",
		NULL, &ai_balrog_missile, NULL },
	{ &SPR_CoreThing, NOSHEET, PAL2, 1, "Fire Whirr",
		NULL, &ai_firewhirr, &ondeath_default },
	{ &SPR_CoreThingShot, NOSHEET, PAL2, 1, "Fire Whirr Projectile",
		&onspawn_persistent, &ai_firewhirr_shot, NULL },
	{ &SPR_GaudiArmor, 	NOSHEET, PAL2, 1, "Gaudi Armor",
		NULL, &ai_gaudiArmored, NULL },
	{ NULL, 		NOSHEET, PAL2, 1, "Gaudi Armor Projectile",
		&onspawn_persistent, NULL, NULL },
	{ &SPR_GaudiEgg, NOSHEET, PAL2, 1, "Gaudi Egg",
		NULL, &ai_gaudi_egg, NULL },
	/* 0x0B0 (176) */
	{ &SPR_BuyoBase, NOSHEET, PAL2, 1, "Buyobuyo Base",
		NULL, &ai_buyobuyo_base, NULL },
	{ &SPR_Buyo, 	NOSHEET, PAL2, 1, "Buyobuyo",
		NULL, &ai_buyobuyo, &ondeath_default },
	{ &SPR_CoreShot1, NOSHEET, PAL3, 1, "Core Spinning Projectile",
		&onspawn_persistent, &ai_minicore_shot, NULL },
	{ &SPR_CoreShot2, NOSHEET, PAL3, 1, "Core Wisp Projectile",
		&onspawn_persistent, &ai_core_ghostie, NULL },
	{ &SPR_Curly, 	NOSHEET, PAL3, 1, "Curly (AI)",
		&onspawn_persistent, &ai_curly_ai, NULL },
	{ &SPR_Polar, 	NOSHEET, PAL0, 1, "Curly Polar Star",
		&onspawn_persistent, &ai_cai_gun, NULL },
	{ &SPR_MGun, 	NOSHEET, PAL1, 1, "Curly Machine Gun",
		&onspawn_persistent, &ai_cai_gun, NULL },
	{ &SPR_Bubble, 	NOSHEET, PAL0, 1, "Curly Bubble Shield",
		&onspawn_persistent, &ai_cai_watershield, NULL },
	{ NULL, 		NOSHEET, PAL2, 1, "Shutter (Large)",
		NULL, &ai_shutter, NULL },
	{ NULL, 		NOSHEET, PAL2, 1, "Shutter (Small)",
		NULL, &ai_shutter, NULL },
	{ &SPR_Baby, 		NOSHEET, PAL2, 1, "Lift Block",
		NULL, &ai_shutter, NULL },
	{ &SPR_FuzzCore, NOSHEET, PAL2, 1, "Fuzz Core",
		NULL, &ai_fuzz_core, &ondeath_default },
	{ &SPR_Fuzz, 	NOSHEET, PAL2, 1, "Fuzz",
		NULL, &ai_fuzz, &ondeath_default },
	{ &SPR_CoreShot4, NOSHEET, PAL3, 1, "Homing Flame Projectile",
		&onspawn_persistent, &ai_core_blast, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "Surface Robot",
		NULL, &ai_almond_robot, NULL },
	{ NULL, 		NOSHEET, PAL0, 2, "Water Level",
		&onspawn_persistent, &ai_waterlevel, NULL },
	/* 0x0C0 (192) */
	{ &SPR_Buggy, 	NOSHEET, PAL1, 1, "Scooter",
		NULL, &ai_motorbike, NULL },
	{ &SPR_Buggy2, 	NOSHEET, PAL1, 2, "Scooter (Pieces)",
		NULL, NULL, NULL },
	{ &SPR_Robot, 	NOSHEET, PAL3, 1, "Blue Robot (Pieces)",
		NULL, NULL, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "Grate Mouth",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Motion Wall",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Porcupine Fish",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Ironhead Projectile",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 0, "Underwater Current",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Dragon Zombie",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Dragon Zombie (Dead)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Dragon Zombie Projectile",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Blue Hopping Critter",
		&onspawn_snap, &ai_critter, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Falling Spike (Small)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Falling Spike (Large)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Counter Bomb",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Countdown Balloon",
		NULL, NULL, &ondeath_default },
	// 0x0D0 (208) */
	{ NULL, 		NOSHEET, PAL0, 1, "Basu (2)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Basu Projectile (2)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Green Beetle (Follow 2)",
		NULL, NULL, &ondeath_default },
	{ &SPR_Spikes, 	NOSHEET, PAL1, 1, "Spikes",
		&onspawn_spike, NULL, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "Sky Dragon",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Night Spirit",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Night Spirit Projectile",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 2, "White Sandcroc",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Debug Cat",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Itoh",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 0, "Smoke/Current Generator",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Shovel Brigade",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Shovel Brigade (Walking)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Prison Bars",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Momorin",
		NULL, NULL, &ondeath_default },
	/* 0x0E0 (224) */
	{ NULL, 		NOSHEET, PAL0, 1, "Chie",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Megane",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Kanpachi",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Bucket",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Droll (Guard)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Flower Sprouts",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Blooming Red Flowers",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Rocket",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Orangebell",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Picked Red Flowers",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Midorin",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Gunfish",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Gunfish Projectile",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Lethal Press",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Cage Bars",
		NULL, NULL, &ondeath_default },
	/* 0x0F0 (240) */
	{ NULL, 		NOSHEET, PAL0, 1, "Jailed Mimiga",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Critter",
		&onspawn_snap, &ai_critter, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Bat",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Bat Generator",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Acid Drop",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 0, "Acid Drop Generator",
		NULL, NULL, &ondeath_default },
	{ &SPR_Press, 	NOSHEET, PAL1, 1, "Press (Proximity)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Misery (Boss)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Misery (Vanish)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Misery Energy Shot",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Misery Lightning Ball",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 4, "Misery Lightning",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Energy Capsule",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 4, "Helicopter",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	/* 0x100 (256) */
	{ NULL, 		NOSHEET, PAL0, 1, "Doctor (Before Fight)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Crystal",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Sleeping Mimiga",
		NULL, NULL, &ondeath_default },
	{ &SPR_Curly, 	NOSHEET, PAL3, 1, "Curly (Carried)",
		&onspawn_persistent, &ai_curly_carried, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "Shovel Brigade (Caged)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Chie (Caged)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Chaco (Caged)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Doctor (Boss)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Doctor Red Wave",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Doctor Red Ball (Fast)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Doctor Red Ball (Slow)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Muscle Doctor (Boss)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 4, "Igor",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Energy Bat",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Energy",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Underwater Block",
		NULL, NULL, &ondeath_default },
	/* 0x110 (272) */
	{ NULL, 		NOSHEET, PAL0, 0, "Water Block Generator",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Droll Projectile",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Droll",
		NULL, NULL, &ondeath_default },
	{ &SPR_Puppy, 	NOSHEET, PAL1, 1, "Puppy (With Item)",
		&onspawn_puppy, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Demon",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Demon Projectile",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Little Family",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Falling Block (Large)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Sue (Teleport In)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Doctor (Red Energy)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 2, "Mini Undead Core",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Misery (Transformed)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Sue (Transformed)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Orange Spinning Shot",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Orange Dot",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Orange Smoke",
		NULL, NULL, &ondeath_default },
	/* 0x120 (288) */
	{ NULL, 		NOSHEET, PAL0, 1, "Glowing Rock Shot",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Orange Critter",
		&onspawn_snap, &ai_critter, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Orange Bat",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 2, "Mini Core (Before Fight)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 0, "Quake",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Huge Energy Shot",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 0, "Falling Block Generator",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Cloud",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 0, "Cloud Generator",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Doctor (Uncrowned)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Balrog/Misery (Bubble)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Demon Crown",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Fish Missile (Orange)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	/* 0x130 (304) */
	{ NULL, 		NOSHEET, PAL0, 1, "Gaudi (Sitting)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Puppy (Small)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 2, "Balrog (Nurse)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Santa (Caged)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Stumpy",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Bute",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Bute (Sword)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Bute (Archer)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Bute Projectile",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Ma Pignon",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Falling (?)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Hopping Enemy (?)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Bute (Defeated)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Mesa",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Mesa (Defeated)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	/* 0x140 (320) */
	{ &SPR_Curly, 	NOSHEET, PAL3, 1, "Curly (Hell)",
		NULL, NULL, NULL },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Deleet",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Bute (Generated)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 0, "Bute Generator",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Heavy Press Projectile",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Itoh/Sue (Ending)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Transmogrifier",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Building Fan",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Rolling",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Ballos Bone Shot",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Ballos Shockwave",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 4, "Ballos Lightning",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Sweat",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Ika-chan",
		NULL, NULL, &ondeath_default },
	/* 0x150 (336) */
	{ NULL, 		NOSHEET, PAL0, 0, "Ika-chan Generator",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Numahachi",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Green Devil",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 0, "Green Devil Generator",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Ballos (Boss)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Ballos Skull Shot",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Hoppy",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Ballos Spikes",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Statue",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Bute (Archer)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 2, "Statue (Breakable)",
		NULL, NULL, &ondeath_default },
	/* 0x160 (352) */
	{ NULL, 		NOSHEET, PAL0, 1, "King (Sword)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Red Bute (Sword)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 0, "Kill Zone",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "???",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 2, "Balrog (Rescue)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Puppy (Ghost)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 1, "Misery (Wind)",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 0, "Water Drop Generator",
		NULL, NULL, &ondeath_default },
	{ NULL, 		NOSHEET, PAL0, 2, "Thank You",
		NULL, NULL, &ondeath_default },
	/* ^ 0x168 (360) ^ */
	/* MAJOR BOSSES - Don't exist in npc.tbl, but need AI methods */
	/* 0x169 (361) */
	{ &SPR_Omega, 	NOSHEET, PAL3, 3, "Omega",
		&onspawn_omega, &ai_omega, &ondeath_omega },
	{ &SPR_Balfrog1, NOSHEET, PAL3, 3, "Balfrog",
		&onspawn_balfrog, &ai_balfrog, &ondeath_balfrog },
	{ NULL, NOSHEET, PAL3, 3, "Monster X",
		NULL, NULL, NULL },
	{ NULL, NOSHEET, PAL3, 3, "Core (Controller)",
		&onspawn_core, &ai_core, &ondeath_core },
	{ NULL, NOSHEET, PAL3, 3, "Ironhead",
		NULL, NULL, NULL },
	{ NULL, NOSHEET, PAL3, 3, "Sisters",
		NULL, NULL, NULL },
	{ NULL, NOSHEET, PAL3, 3, "Undead Core",
		NULL, NULL, NULL },
	{ NULL, NOSHEET, PAL3, 3, "Heavy Press",
		NULL, NULL, NULL },
	{ NULL, NOSHEET, PAL3, 3, "Ballos",
		NULL, NULL, NULL },
	/* ^ 0x171 (369) ^ */
	/* BOSS PARTS - Separate entities belonging to the bosses which don't
	 * already exist in the NPC table, for whatever reason */
	/* 0x172 (370) */
	{ NULL, NOSHEET, PAL3, 3, "Core (Front)",
		&onspawn_persistent, &ai_core_front, NULL },
	{ NULL, NOSHEET, PAL3, 3, "Core (Back)",
		&onspawn_persistent, &ai_core_back, NULL },
	{ &SPR_MiniCore, NOSHEET, PAL3, 2, "Mini Core",
		&onspawn_persistent, &ai_minicore, NULL },
};
