#include "tables.h"
#include "resources.h"

const song_info_def song_info[SONG_COUNT] = {
	{ NULL, 			"Silence" },
	{ BGM_Mischievous, 	"Mischievous Robot" },
	{ BGM_Safety, 		"Safety" },
	{ BGM_GameOver, 	"Game Over" },
	{ BGM_Gravity, 		"Gravity" },
	{ BGM_Grasstown, 	"On To Grasstown" },
	{ BGM_Meltdown2, 	"Meltdown 2" },
	{ BGM_EyesOfFlame, 	"Eyes Of Flame" },
	{ BGM_Gestation, 	"Gestation" },
	{ BGM_Mimiga, 		"Mimiga Village" },
	{ BGM_Fanfare1, 	"Fanfare 1" },
	{ BGM_Balrog, 		"Balrog's Theme" },
	{ BGM_Cemetery, 	"Cemetery" },
	{ BGM_Plant, 		"Yamashita Farm" },
	{ BGM_Pulse, 		"Pulse" },
	{ BGM_Fanfare3, 	"Fanfare 2" },
	{ BGM_Fanfare2, 	"Fanfare 3" }, // 0x10
	{ BGM_Tyrant, 		"Tyrant" },
	{ BGM_Run, 			"Run!" },
	{ BGM_Jenka1, 		"Jenka 1" },
	{ BGM_LabFight, 	"Labyrinth Fight" },
	{ BGM_Access, 		"Access" },
	{ BGM_Oppression, 	"Oppression" },
	{ BGM_Geothermal, 	"Geothermal" },
	{ BGM_CaveStory, 	"Cave Story" },
	{ BGM_MoonSong, 	"Moon Song" },
	{ BGM_HerosEnd, 	"Hero's End" },
	{ BGM_Scorching, 	"Scorching Back" },
	{ BGM_Quiet, 		"Quiet" },
	{ BGM_Balcony, 		"Last Cave" },
	{ BGM_Balcony, 		"Balcony" },
	{ BGM_Charge, 		"Charge" },
	{ BGM_EyesOfFlame, 	"Last Battle" }, // 0x20
	{ BGM_Balcony, 		"The Way Back Home" },
	{ BGM_Zombie, 		"Zombie" },
	{ BGM_BreakDown, 	"Break Down" },
	{ BGM_Balcony, 		"Running Hell" },
	{ BGM_Jenka2, 		"Jenka 2" },
	{ BGM_Waterway, 	"Living Waterway" },
	{ BGM_Balcony, 		"Seal Chamber" },
	{ BGM_Balcony, 		"Toroko's Theme" },
	{ BGM_Balcony, 		"White Stone Wall" },
};
