#include "common.h"
#include "bank_data.h"
#include "resources.h"
#include "tables.h"

const stage_info_def stage_info[STAGE_COUNT] = {
	{ NULL,			NULL,		NULL,		NULL,NULL,NULL,NULL,NULL,NULL,		&PAL_Regu,	0,	0,	"" },
	{ PXM_Pens1,	PXE_Pens1,	TSC_Pens1,	JTSC_Pens1, STSC_Pens1, PTSC_Pens1, FTSC_Pens1, ITSC_Pens1, GTSC_Pens1,	&PAL_LabB,	16,	14,	"Arthur's House" },
	{ PXM_Eggs,		PXE_Eggs,	TSC_Eggs,	JTSC_Eggs, STSC_Eggs, PTSC_Eggs, FTSC_Eggs, ITSC_Eggs, GTSC_Eggs,	&PAL_Regu,	6,	13,	"Egg Corridor" },
	{ PXM_EggX,		PXE_EggX,	TSC_EggX,	JTSC_EggX, STSC_EggX, PTSC_EggX, FTSC_EggX, ITSC_EggX, GTSC_EggX,	&PAL_Regu,	7,	0,	"Egg No. 00" },
	{ PXM_Egg6,		PXE_Egg6,	TSC_Egg6,	JTSC_Egg6, STSC_Egg6, PTSC_Egg6, FTSC_Egg6, ITSC_Egg6, GTSC_Egg6,	&PAL_Regu,	5,	0,	"Egg No. 06" },
	{ PXM_EggR,		PXE_EggR,	TSC_EggR,	JTSC_EggR, STSC_EggR, PTSC_EggR, FTSC_EggR, ITSC_EggR, GTSC_EggR,	&PAL_Regu,	19,	0,	"Egg Observatory" },
	{ PXM_Weed,		PXE_Weed,	TSC_Weed,	JTSC_Weed, STSC_Weed, PTSC_Weed, FTSC_Weed, ITSC_Weed, GTSC_Weed,	&PAL_Regu,	20,	2,	"Grasstown" },
	{ PXM_Santa,	PXE_Santa,	TSC_Santa,	JTSC_Santa, STSC_Santa, PTSC_Santa, FTSC_Santa, ITSC_Santa, GTSC_Santa,	&PAL_Regu,	2,	0,	"Santa's House" },
	{ PXM_Chako,	PXE_Chako,	TSC_Chako,	JTSC_Chako, STSC_Chako, PTSC_Chako, FTSC_Chako, ITSC_Chako, GTSC_Chako,	&PAL_Chaco,	2,	0,	"Chako's House" },
	{ PXM_MazeI,	PXE_MazeI,	TSC_MazeI,	JTSC_MazeI, STSC_MazeI, PTSC_MazeI, FTSC_MazeI, ITSC_MazeI, GTSC_MazeI,	&PAL_XB,	13,	9,	"Labyrinth I" },
	{ PXM_Sand,		PXE_Sand,	TSC_Sand,	JTSC_Sand, STSC_Sand, PTSC_Sand, FTSC_Sand, ITSC_Sand, GTSC_Sand,	&PAL_Regu,	18,	16,	"Sand Zone" },
	{ PXM_Mimi,		PXE_Mimi,	TSC_Mimi,	JTSC_Mimi, STSC_Mimi, PTSC_Mimi, FTSC_Mimi, ITSC_Mimi, GTSC_Mimi,	&PAL_Regu,	14,	2,	"Mimiga Village" },
	{ PXM_Cave,		PXE_Cave,	TSC_Cave,	JTSC_Cave, STSC_Cave, PTSC_Cave, FTSC_Cave, ITSC_Cave, GTSC_Cave,	&PAL_Regu,	3,	0,	"First Cave" },
	{ PXM_Start,	PXE_Start,	TSC_Start,	JTSC_Start, STSC_Start, PTSC_Start, FTSC_Start, ITSC_Start, GTSC_Start,	&PAL_Regu,	3,	0,	"Start Point" },
	{ PXM_Barr,		PXE_Barr,	TSC_Barr,	JTSC_Barr, STSC_Barr, PTSC_Barr, FTSC_Barr, ITSC_Barr, GTSC_Barr,	&PAL_Regu,	14,	0,	"Shack" },
	{ PXM_Pool,		PXE_Pool,	TSC_Pool,	JTSC_Pool, STSC_Pool, PTSC_Pool, FTSC_Pool, ITSC_Pool, GTSC_Pool,	&PAL_Regu,	14,	2,	"Reservoir" },
	/* 0x10 (16) */
	{ PXM_Cemet,	PXE_Cemet,	TSC_Cemet,	JTSC_Cemet, STSC_Cemet, PTSC_Cemet, FTSC_Cemet, ITSC_Cemet, GTSC_Cemet,	&PAL_Regu,	14,	0,	"Graveyard" },
	{ PXM_Plant,	PXE_Plant,	TSC_Plant,	JTSC_Plant, STSC_Plant, PTSC_Plant, FTSC_Plant, ITSC_Plant, GTSC_Plant,	&PAL_Plant,	14,	2,	"Yamashita Farm" },
	{ PXM_Shelt,	PXE_Shelt,	TSC_Shelt,	JTSC_Shelt, STSC_Shelt, PTSC_Shelt, FTSC_Shelt, ITSC_Shelt, GTSC_Shelt,	&PAL_Regu,	19,	0,	"Shelter" },
	{ PXM_Comu,		PXE_Comu,	TSC_Comu,	JTSC_Comu, STSC_Comu, PTSC_Comu, FTSC_Comu, ITSC_Comu, GTSC_Comu,	&PAL_Regu,	16,	0,	"Assembly Hall" },
	{ PXM_MiBox,	PXE_MiBox,	TSC_MiBox,	JTSC_MiBox, STSC_MiBox, PTSC_MiBox, FTSC_MiBox, ITSC_MiBox, GTSC_MiBox,	&PAL_Regu,	14,	0,	"Shack" },
	{ PXM_EgEnd1,	PXE_EgEnd1,	TSC_EgEnd1,	JTSC_EgEnd1, STSC_EgEnd1, PTSC_EgEnd1, FTSC_EgEnd1, ITSC_EgEnd1, GTSC_EgEnd1,&PAL_Regu,	19,	0,	"Side Room" },
	{ PXM_Cthu,		PXE_Cthu,	TSC_Cthu,	JTSC_Cthu, STSC_Cthu, PTSC_Cthu, FTSC_Cthu, ITSC_Cthu, GTSC_Cthu,	&PAL_Regu,	19,	0,	"Cthulhu's Abode" },
	{ PXM_Egg1,		PXE_Egg1,	TSC_Egg1,	JTSC_Egg1, STSC_Egg1, PTSC_Egg1, FTSC_Egg1, ITSC_Egg1, GTSC_Egg1,	&PAL_Regu,	5,	0,	"Egg No. 01" },
	{ PXM_Pens2,	PXE_Pens2,	TSC_Pens2,	JTSC_Pens2, STSC_Pens2, PTSC_Pens2, FTSC_Pens2, ITSC_Pens2, GTSC_Pens2,	&PAL_LabB,	16,	14,	"Arthur's House" },
	{ PXM_Malco,	PXE_Malco,	TSC_Malco,	JTSC_Malco, STSC_Malco, PTSC_Malco, FTSC_Malco, ITSC_Malco, GTSC_Malco,	&PAL_Regu,	2,	0,	"Power Room" },
	{ PXM_WeedS,	PXE_WeedS,	TSC_WeedS,	JTSC_WeedS, STSC_WeedS, PTSC_WeedS, FTSC_WeedS, ITSC_WeedS, GTSC_WeedS,	&PAL_Regu,	2,	0,	"Save Point" },
	{ PXM_WeedD,	PXE_WeedD,	TSC_WeedD,	JTSC_WeedD, STSC_WeedD, PTSC_WeedD, FTSC_WeedD, ITSC_WeedD, GTSC_WeedD,	&PAL_Regu,	19,	0,	"ExecutionChamber" },
	{ PXM_Frog,		PXE_Frog,	TSC_Frog,	JTSC_Frog, STSC_Frog, PTSC_Frog, FTSC_Frog, ITSC_Frog, GTSC_Frog,	&PAL_Frog,	20,	2,	"Gum" },
	{ PXM_Curly,	PXE_Curly,	TSC_Curly,	JTSC_Curly, STSC_Curly, PTSC_Curly, FTSC_Curly, ITSC_Curly, GTSC_Curly,	&PAL_Regu,	18,	0,	"Sand Zone Bar" },
	{ PXM_WeedB,	PXE_WeedB,	TSC_WeedB,	JTSC_WeedB, STSC_WeedB, PTSC_WeedB, FTSC_WeedB, ITSC_WeedB, GTSC_WeedB,	&PAL_Regu,	16,	0,	"Grasstown Hut" },
	{ PXM_Stream,	PXE_Stream,	TSC_Stream,	JTSC_Stream, STSC_Stream, PTSC_Stream, FTSC_Stream, ITSC_Stream, GTSC_Stream,&PAL_Regu,	17,	3,	"Main Artery" },
	/* 0x20 (32) */
	{ PXM_CurlyS,	PXE_CurlyS,	TSC_CurlyS,	JTSC_CurlyS, STSC_CurlyS, PTSC_CurlyS, FTSC_CurlyS, ITSC_CurlyS, GTSC_CurlyS,&PAL_Regu,	16,	0,	"Small Room" },
	{ PXM_Jenka1,	PXE_Jenka1,	TSC_Jenka1,	JTSC_Jenka1, STSC_Jenka1, PTSC_Jenka1, FTSC_Jenka1, ITSC_Jenka1, GTSC_Jenka1,&PAL_Jenka,	2,	0,	"Jenka's House" },
	{ PXM_Dark,		PXE_Dark,	TSC_Dark,	JTSC_Dark, STSC_Dark, PTSC_Dark, FTSC_Dark, ITSC_Dark, GTSC_Dark,	&PAL_Regu,	18,	0,	"Deserted House" },
	{ PXM_Gard,		PXE_Gard,	TSC_Gard,	JTSC_Gard, STSC_Gard, PTSC_Gard, FTSC_Gard, ITSC_Gard, GTSC_Gard,	&PAL_Regu,	9,	5,	"Storehouse" },
	{ PXM_Jenka2,	PXE_Jenka2,	TSC_Jenka2,	JTSC_Jenka2, STSC_Jenka2, PTSC_Jenka2, FTSC_Jenka2, ITSC_Jenka2, GTSC_Jenka2,&PAL_Jenka,	2,	0,	"Jenka's House" },
	{ PXM_SandE,	PXE_SandE,	TSC_SandE,	JTSC_SandE, STSC_SandE, PTSC_SandE, FTSC_SandE, ITSC_SandE, GTSC_SandE,	&PAL_Regu,	18,	16,	"Sand Zone" },
	{ PXM_MazeH,	PXE_MazeH,	TSC_MazeH,	JTSC_MazeH, STSC_MazeH, PTSC_MazeH, FTSC_MazeH, ITSC_MazeH, GTSC_MazeH,	&PAL_XB,	13,	9,	"Labyrinth H" },
	{ PXM_MazeW,	PXE_MazeW,	TSC_MazeW,	JTSC_MazeW, STSC_MazeW, PTSC_MazeW, FTSC_MazeW, ITSC_MazeW, GTSC_MazeW,	&PAL_X,		13,	8,	"Labyrinth W" },
	{ PXM_MazeO,	PXE_MazeO,	TSC_MazeO,	JTSC_MazeO, STSC_MazeO, PTSC_MazeO, FTSC_MazeO, ITSC_MazeO, GTSC_MazeO,	&PAL_Regu,	13,	0,	"Camp" },
	{ PXM_MazeD,	PXE_MazeD,	TSC_MazeD,	JTSC_MazeD, STSC_MazeD, PTSC_MazeD, FTSC_MazeD, ITSC_MazeD, GTSC_MazeD,	&PAL_Dark,	13,	0,	"Clinic Ruins" },
	{ PXM_MazeA,	PXE_MazeA,	TSC_MazeA,	JTSC_MazeA, STSC_MazeA, PTSC_MazeA, FTSC_MazeA, ITSC_MazeA, GTSC_MazeA,	&PAL_Maze,	19,	0,	"Labyrinth Shop" },
	{ PXM_MazeB,	PXE_MazeB,	TSC_MazeB,	JTSC_MazeB, STSC_MazeB, PTSC_MazeB, FTSC_MazeB, ITSC_MazeB, GTSC_MazeB,	&PAL_LabB,	13,	14,	"Labyrinth B" },
	{ PXM_MazeS,	PXE_MazeS,	TSC_MazeS,	JTSC_MazeS, STSC_MazeS, PTSC_MazeS, FTSC_MazeS, ITSC_MazeS, GTSC_MazeS,	&PAL_Boulder,13,6,	"Boulder Chamber" },
	{ PXM_MazeM,	PXE_MazeM,	TSC_MazeM,	JTSC_MazeM, STSC_MazeM, PTSC_MazeM, FTSC_MazeM, ITSC_MazeM, GTSC_MazeM,	&PAL_MazeM,	24,	10,	"Labyrinth M" },
	{ PXM_Drain,	PXE_Drain,	TSC_Drain,	JTSC_Drain, STSC_Drain, PTSC_Drain, FTSC_Drain, ITSC_Drain, GTSC_Drain,	&PAL_Regu,	3,	11,	"Dark Place" },
	{ PXM_Almond,	PXE_Almond,	TSC_Almond,	JTSC_Almond, STSC_Almond, PTSC_Almond, FTSC_Almond, ITSC_Almond, GTSC_Almond,&PAL_Regu,	1,	11,	"Core" },
	/* 0x30 (48) */
	{ PXM_River,	PXE_River,	TSC_River,	JTSC_River, STSC_River, PTSC_River, FTSC_River, ITSC_River, GTSC_River,	&PAL_Regu,	17,	2,	"Waterway" },
	{ PXM_Eggs2,	PXE_Eggs2,	TSC_Eggs2,	JTSC_Eggs2, STSC_Eggs2, PTSC_Eggs2, FTSC_Eggs2, ITSC_Eggs2, GTSC_Eggs2,	&PAL_Eggs2,	23,	13,	"Egg Corridor?" },
	{ PXM_Cthu2,	PXE_Cthu2,	TSC_Cthu2,	JTSC_Cthu2, STSC_Cthu2, PTSC_Cthu2, FTSC_Cthu2, ITSC_Cthu2, GTSC_Cthu2,	&PAL_Regu,	19,	0,	"Cthulhu's Abode?" },
	{ PXM_EggR2,	PXE_EggR2,	TSC_EggR2,	JTSC_EggR2, STSC_EggR2, PTSC_EggR2, FTSC_EggR2, ITSC_EggR2, GTSC_EggR2,	&PAL_Sisters,19,0,	"Egg Observatory?" },
	{ PXM_EggX,		PXE_EggX2,	TSC_EggX2,	JTSC_EggX2, STSC_EggX2, PTSC_EggX2, FTSC_EggX2, ITSC_EggX2, GTSC_EggX2,	&PAL_Regu,	22,	0,	"Egg No. 00" },
	{ PXM_Oside,	PXE_Oside,	TSC_Oside,	JTSC_Oside, STSC_Oside, PTSC_Oside, FTSC_Oside, ITSC_Oside, GTSC_Oside,	&PAL_Regu,	15,	7,	"Outer Wall" },
	{ PXM_EgEnd2,	PXE_EgEnd2,	TSC_EgEnd2,	JTSC_EgEnd2, STSC_EgEnd2, PTSC_EgEnd2, FTSC_EgEnd2, ITSC_EgEnd2, GTSC_EgEnd2,&PAL_Regu,	19,	0,	"Side Room" },
	{ PXM_Itoh,		PXE_Itoh,	TSC_Itoh,	JTSC_Itoh, STSC_Itoh, PTSC_Itoh, FTSC_Itoh, ITSC_Itoh, GTSC_Itoh,	&PAL_LabB,	19,	14,	"Storehouse" },
	{ PXM_Cent,		PXE_Cent,	TSC_Cent,	JTSC_Cent, STSC_Cent, PTSC_Cent, FTSC_Cent, ITSC_Cent, GTSC_Cent,	&PAL_Regu,	4,	2,	"Plantation" },
	{ PXM_Jail1,	PXE_Jail1,	TSC_Jail1,	JTSC_Jail1, STSC_Jail1, PTSC_Jail1, FTSC_Jail1, ITSC_Jail1, GTSC_Jail1,	&PAL_Regu,	11,	0,	"Jail No. 1" },
	{ PXM_Momo,		PXE_Momo,	TSC_Momo,	JTSC_Momo, STSC_Momo, PTSC_Momo, FTSC_Momo, ITSC_Momo, GTSC_Momo,	&PAL_Regu,	11,	0,	"Hideout" },
	{ PXM_Lounge,	PXE_Lounge,	TSC_Lounge,	JTSC_Lounge, STSC_Lounge, PTSC_Lounge, FTSC_Lounge, ITSC_Lounge, GTSC_Lounge,&PAL_Regu,	11,	0,	"Rest Area" },
	{ PXM_CentW,	PXE_CentW,	TSC_CentW,	JTSC_CentW, STSC_CentW, PTSC_CentW, FTSC_CentW, ITSC_CentW, GTSC_CentW,	&PAL_Regu,	19,	0,	"Teleporter" },
	{ PXM_Jail2,	PXE_Jail2,	TSC_Jail2,	JTSC_Jail2, STSC_Jail2, PTSC_Jail2, FTSC_Jail2, ITSC_Jail2, GTSC_Jail2,	&PAL_Regu,	19,	0,	"Jail No. 2" },
	{ PXM_Blcny1,	PXE_Blcny1,	TSC_Blcny1,	JTSC_Blcny1, STSC_Blcny1, PTSC_Blcny1, FTSC_Blcny1, ITSC_Blcny1, GTSC_Blcny1,&PAL_Regu,	21,	4,	"Balcony" },
	{ PXM_Priso1,	PXE_Priso1,	TSC_Priso1,	JTSC_Priso1, STSC_Priso1, PTSC_Priso1, FTSC_Priso1, ITSC_Priso1, GTSC_Priso1,&PAL_Red,	11,	0,	"Last Cave" },
	/* 0x40 (64) */
	{ PXM_Ring1,	PXE_Ring1,	TSC_Ring1,	JTSC_Ring1, STSC_Ring1, PTSC_Ring1, FTSC_Ring1, ITSC_Ring1, GTSC_Ring1,	&PAL_Miza,	25,	4,	"Throne Room" },
	{ PXM_Ring2,	PXE_Ring2,	TSC_Ring2,	JTSC_Ring2, STSC_Ring2, PTSC_Ring2, FTSC_Ring2, ITSC_Ring2, GTSC_Ring2,	&PAL_Regu,	27,	4,	"The King's Table" },
	{ PXM_Prefa1,	PXE_Prefa1,	TSC_Prefa1,	JTSC_Prefa1, STSC_Prefa1, PTSC_Prefa1, FTSC_Prefa1, ITSC_Prefa1, GTSC_Prefa1,&PAL_Regu,	16,	0,	"Prefab House" },
	{ PXM_Priso2,	PXE_Priso2,	TSC_Priso2,	JTSC_Priso2, STSC_Priso2, PTSC_Priso2, FTSC_Priso2, ITSC_Priso2, GTSC_Priso2,&PAL_Red,	11,	0,	"LastCave(Hidden)" },
	{ PXM_Ring3,	PXE_Ring3,	TSC_Ring3,	JTSC_Ring3, STSC_Ring3, PTSC_Ring3, FTSC_Ring3, ITSC_Ring3, GTSC_Ring3,	&PAL_Miza,	28,	0,	"Black Space" },
	{ PXM_Little,	PXE_Little,	TSC_Little,	JTSC_Little, STSC_Little, PTSC_Little, FTSC_Little, ITSC_Little, GTSC_Little,&PAL_Regu,	16,	0,	"Little House" },
	{ PXM_Blcny2,	PXE_Blcny2,	TSC_Blcny2,	JTSC_Blcny2, STSC_Blcny2, PTSC_Blcny2, FTSC_Blcny2, ITSC_Blcny2, GTSC_Blcny2,&PAL_Regu,	21,	4,	"Balcony" },
	{ PXM_Fall,		PXE_Fall,	TSC_Fall,	JTSC_Fall, STSC_Fall, PTSC_Fall, FTSC_Fall, ITSC_Fall, GTSC_Fall,	&PAL_Regu,	8,	15,	"Ending" },
	{ PXM_Kings,	PXE_Kings,	TSC_Kings,	JTSC_Kings, STSC_Kings, PTSC_Kings, FTSC_Kings, ITSC_Kings, GTSC_Kings,	&PAL_Regu,	25,	0,	"Intro" },
	{ PXM_Pixel,	PXE_Pixel,	TSC_Pixel,	JTSC_Pixel, STSC_Pixel, PTSC_Pixel, FTSC_Pixel, ITSC_Pixel, GTSC_Pixel,	&PAL_Regu,	16,	0,	"Waterway Cabin" },
	{ PXM_e_Maze,	PXE_e_Maze,	TSC_e_Maze,	JTSC_e_Maze, STSC_e_Maze, PTSC_e_Maze, FTSC_e_Maze, ITSC_e_Maze, GTSC_e_Maze,&PAL_Regu,	13,	0,	"Credits" },
	{ PXM_e_Jenk,	PXE_e_Jenk,	TSC_e_Jenk,	JTSC_e_Jenk, STSC_e_Jenk, PTSC_e_Jenk, FTSC_e_Jenk, ITSC_e_Jenk, GTSC_e_Jenk,&PAL_Regu,	2,	0,	"Credits" },
	{ PXM_e_Malc,	PXE_e_Malc,	TSC_e_Malc,	JTSC_e_Malc, STSC_e_Malc, PTSC_e_Malc, FTSC_e_Malc, ITSC_e_Malc, GTSC_e_Malc,&PAL_Regu,	2,	0,	"Credits" },
	{ PXM_e_Ceme,	PXE_e_Ceme,	TSC_e_Ceme,	JTSC_e_Ceme, STSC_e_Ceme, PTSC_e_Ceme, FTSC_e_Ceme, ITSC_e_Ceme, GTSC_e_Ceme,&PAL_Regu,	14,	0,	"Credits" },
	{ PXM_e_Sky,	PXE_e_Sky,	TSC_e_Sky,	JTSC_e_Sky, STSC_e_Sky, PTSC_e_Sky, FTSC_e_Sky, ITSC_e_Sky, GTSC_e_Sky,	&PAL_Regu,	8,	0,	"Credits" },
	{ PXM_Prefa2,	PXE_Prefa2,	TSC_Prefa2,	JTSC_Prefa2, STSC_Prefa2, PTSC_Prefa2, FTSC_Prefa2, ITSC_Prefa2, GTSC_Prefa2,&PAL_Regu,	16,	0,	"Prefab House" },
	/* 0x50 (80) */
	{ PXM_Hell1,	PXE_Hell1,	TSC_Hell1,	JTSC_Hell1, STSC_Hell1, PTSC_Hell1, FTSC_Hell1, ITSC_Hell1, GTSC_Hell1,	&PAL_Regu,	10,	12,	"Sacred Ground B1" },
	{ PXM_Hell2,	PXE_Hell2,	TSC_Hell2,	JTSC_Hell2, STSC_Hell2, PTSC_Hell2, FTSC_Hell2, ITSC_Hell2, GTSC_Hell2,	&PAL_Regu,	10,	12,	"Sacred Ground B2" },
	{ PXM_Hell3,	PXE_Hell3,	TSC_Hell3,	JTSC_Hell3, STSC_Hell3, PTSC_Hell3, FTSC_Hell3, ITSC_Hell3, GTSC_Hell3,	&PAL_Regu,	10,	12,	"Sacred Ground B3" },
	{ PXM_Mapi,		PXE_Mapi,	TSC_Mapi,	JTSC_Mapi, STSC_Mapi, PTSC_Mapi, FTSC_Mapi, ITSC_Mapi, GTSC_Mapi,	&PAL_Mapi,	3,	0,	"Storage" },
	{ PXM_Hell4,	PXE_Hell4,	TSC_Hell4,	JTSC_Hell4, STSC_Hell4, PTSC_Hell4, FTSC_Hell4, ITSC_Hell4, GTSC_Hell4,	&PAL_Regu,	10,	0,	"Passage?" },
	{ PXM_Hell42,	PXE_Hell42,	TSC_Hell42,	JTSC_Hell42, STSC_Hell42, PTSC_Hell42, FTSC_Hell42, ITSC_Hell42, GTSC_Hell42,&PAL_Regu,	10,	0,	"Passage?" },
	{ PXM_Statue,	PXE_Statue,	TSC_Statue,	JTSC_Statue, STSC_Statue, PTSC_Statue, FTSC_Statue, ITSC_Statue, GTSC_Statue,&PAL_LabB,	26,	14,	"Statue Chamber" },
	{ PXM_Ballo1,	PXE_Ballo1,	TSC_Ballo1,	JTSC_Ballo1, STSC_Ballo1, PTSC_Ballo1, FTSC_Ballo1, ITSC_Ballo1, GTSC_Ballo1,&PAL_LabB,	10,	14,	"Seal Chamber" },
	{ PXM_Ostep,	PXE_Ostep,	TSC_Ostep,	JTSC_Ostep, STSC_Ostep, PTSC_Ostep, FTSC_Ostep, ITSC_Ostep, GTSC_Ostep,	&PAL_Regu,	25,	4,	"Corridor" },
	{ PXM_e_Labo,	PXE_e_Labo,	TSC_e_Labo,	JTSC_e_Labo, STSC_e_Labo, PTSC_e_Labo, FTSC_e_Labo, ITSC_e_Labo, GTSC_e_Labo,&PAL_Regu,	12,	0,	"Credits" },
	{ PXM_Pole,		PXE_Pole,	TSC_Pole,	JTSC_Pole, STSC_Pole, PTSC_Pole, FTSC_Pole, ITSC_Pole, GTSC_Pole,	&PAL_Gunsmith,3,0,	"Hermit Gunsmith" },
	{ PXM_Island,	PXE_Island,	TSC_Island,	JTSC_Island, STSC_Island, PTSC_Island, FTSC_Island, ITSC_Island, GTSC_Island,&PAL_XX,	21,	0,	"" },
	{ PXM_Ballo2,	PXE_Ballo2,	TSC_Ballo2,	JTSC_Ballo2, STSC_Ballo2, PTSC_Ballo2, FTSC_Ballo2, ITSC_Ballo2, GTSC_Ballo2,&PAL_LabB,	10,	14,	"Seal Chamber" },
	{ PXM_e_Blcn,	PXE_e_Blcn,	TSC_e_Blcn,	JTSC_e_Blcn, STSC_e_Blcn, PTSC_e_Blcn, FTSC_e_Blcn, ITSC_e_Blcn, GTSC_e_Blcn,&PAL_Regu,	21,	0,	"Credits" },
	{ PXM_Clock,	PXE_Clock,	TSC_Clock,	JTSC_Clock, STSC_Clock, PTSC_Clock, FTSC_Clock, ITSC_Clock, GTSC_Clock,	&PAL_Regu,	15,	7,	"Clock" },
};
