extern const uint8_t PXA_Almond[];
extern const uint8_t PXA_Barr[];
extern const uint8_t PXA_Cave[];
extern const uint8_t PXA_Cent[];
extern const uint8_t PXA_EggIn[];
extern const uint8_t PXA_EggX[];
extern const uint8_t PXA_Fall[];
extern const uint8_t PXA_Gard[];
extern const uint8_t PXA_Jail[];
extern const uint8_t PXA_Labo[];
extern const uint8_t PXA_Oside[];
extern const uint8_t PXA_Pens[];
extern const uint8_t PXA_River[];
extern const uint8_t PXA_Sand[];
extern const uint8_t PXA_Store[];
extern const uint8_t PXA_Weed[];

extern const uint8_t PXA_Mimi[];
extern const uint8_t PXM_Barr[];
extern const uint8_t PXM_Cemet[];
extern const uint8_t PXM_e_Ceme[];
extern const uint8_t PXM_MiBox[];
extern const uint8_t PXM_Mimi[];
extern const uint8_t PXM_Plant[];
extern const uint8_t PXM_Pool[];
extern const uint8_t PXA_Eggs[];
extern const uint8_t PXA_Eggs2[];
extern const uint8_t PXM_Eggs[];
extern const uint8_t PXM_Eggs2[];
extern const uint8_t PXA_Maze[];
extern const uint8_t PXM_e_Maze[];
extern const uint8_t PXM_MazeB[];
extern const uint8_t PXM_MazeD[];
extern const uint8_t PXM_MazeH[];
extern const uint8_t PXM_MazeI[];
extern const uint8_t PXM_MazeO[];
extern const uint8_t PXM_MazeS[];
extern const uint8_t PXM_MazeW[];
extern const uint8_t PXA_MazeM[];
extern const uint8_t PXM_MazeM[];
extern const uint8_t PXA_Blcny[];
extern const uint8_t PXM_e_Blcn[];
extern const uint8_t PXM_Blcny1[];
extern const uint8_t PXM_Blcny2[];
extern const uint8_t PXA_Kings[];
extern const uint8_t PXM_Kings[];
extern const uint8_t PXM_Ring1[];
extern const uint8_t PXM_Ostep[];
extern const uint8_t PXA_Ring2[];
extern const uint8_t PXM_Ring2[];
extern const uint8_t PXA_Ring3[];
extern const uint8_t PXM_Ring3[];
extern const uint8_t PXA_Hell[];
extern const uint8_t PXM_Hell1[];
extern const uint8_t PXM_Hell2[];
extern const uint8_t PXM_Hell3[];
extern const uint8_t PXM_Hell4[];
extern const uint8_t PXM_Hell42[];
extern const uint8_t PXM_Ballo1[];
extern const uint8_t PXM_Ballo2[];
extern const uint8_t PXA_Statue[];
extern const uint8_t PXM_Statue[];

extern const uint8_t PXM_Almond[];
extern const uint8_t PXM_Cave[];
extern const uint8_t PXM_Cent[];
extern const uint8_t PXM_CentW[];
extern const uint8_t PXM_Chako[];
extern const uint8_t PXM_Clock[];
extern const uint8_t PXM_Comu[];
extern const uint8_t PXM_Cthu[];
extern const uint8_t PXM_Cthu2[];
extern const uint8_t PXM_Curly[];
extern const uint8_t PXM_CurlyS[];
extern const uint8_t PXM_Dark[];
extern const uint8_t PXM_Drain[];
extern const uint8_t PXM_e_Jenk[];
extern const uint8_t PXM_e_Labo[];
extern const uint8_t PXM_e_Malc[];
extern const uint8_t PXM_e_Sky[];
extern const uint8_t PXM_EgEnd1[];
extern const uint8_t PXM_EgEnd2[];
extern const uint8_t PXM_Egg1[];
extern const uint8_t PXM_Egg6[];
extern const uint8_t PXM_EggR[];
extern const uint8_t PXM_EggR2[];
extern const uint8_t PXM_EggX[];
extern const uint8_t PXM_EggX2[];
extern const uint8_t PXM_Fall[];
extern const uint8_t PXM_Frog[];
extern const uint8_t PXM_Gard[];
extern const uint8_t PXM_Itoh[];
extern const uint8_t PXM_Island[];
extern const uint8_t PXM_Jail1[];
extern const uint8_t PXM_Jail2[];
extern const uint8_t PXM_Jenka1[];
extern const uint8_t PXM_Jenka2[];
extern const uint8_t PXM_Little[];
extern const uint8_t PXM_Lounge[];
extern const uint8_t PXM_Malco[];
extern const uint8_t PXM_Mapi[];
extern const uint8_t PXM_MazeA[];
extern const uint8_t PXM_Momo[];
extern const uint8_t PXM_Oside[];
extern const uint8_t PXM_Pens1[];
extern const uint8_t PXM_Pens2[];
extern const uint8_t PXM_Pixel[];
extern const uint8_t PXM_Pole[];
extern const uint8_t PXM_Prefa1[];
extern const uint8_t PXM_Prefa2[];
extern const uint8_t PXM_Priso1[];
extern const uint8_t PXM_Priso2[];
extern const uint8_t PXM_River[];
extern const uint8_t PXM_Sand[];
extern const uint8_t PXM_SandE[];
extern const uint8_t PXM_Santa[];
extern const uint8_t PXM_Shelt[];
extern const uint8_t PXM_Start[];
extern const uint8_t PXM_Stream[];
extern const uint8_t PXM_Weed[];
extern const uint8_t PXM_WeedB[];
extern const uint8_t PXM_WeedD[];
extern const uint8_t PXM_WeedS[];

extern const uint8_t PXE_0[];
extern const uint8_t PXE_Almond[];
extern const uint8_t PXE_Ballo1[];
extern const uint8_t PXE_Ballo2[];
extern const uint8_t PXE_Barr[];
extern const uint8_t PXE_Blcny1[];
extern const uint8_t PXE_Blcny2[];
extern const uint8_t PXE_Cave[];
extern const uint8_t PXE_Cemet[];
extern const uint8_t PXE_Cent[];
extern const uint8_t PXE_CentW[];
extern const uint8_t PXE_Chako[];
extern const uint8_t PXE_Clock[];
extern const uint8_t PXE_Comu[];
extern const uint8_t PXE_Cthu[];
extern const uint8_t PXE_Cthu2[];
extern const uint8_t PXE_Curly[];
extern const uint8_t PXE_CurlyS[];
extern const uint8_t PXE_Dark[];
extern const uint8_t PXE_Drain[];
extern const uint8_t PXE_e_Blcn[];
extern const uint8_t PXE_e_Ceme[];
extern const uint8_t PXE_e_Jenk[];
extern const uint8_t PXE_e_Labo[];
extern const uint8_t PXE_e_Malc[];
extern const uint8_t PXE_e_Maze[];
extern const uint8_t PXE_e_Sky[];
extern const uint8_t PXE_EgEnd1[];
extern const uint8_t PXE_EgEnd2[];
extern const uint8_t PXE_Egg1[];
extern const uint8_t PXE_Egg6[];
extern const uint8_t PXE_EggR[];
extern const uint8_t PXE_EggR2[];
extern const uint8_t PXE_Eggs[];
extern const uint8_t PXE_Eggs2[];
extern const uint8_t PXE_EggX[];
extern const uint8_t PXE_EggX2[];
extern const uint8_t PXE_Fall[];
extern const uint8_t PXE_Frog[];
extern const uint8_t PXE_Gard[];
extern const uint8_t PXE_Hell1[];
extern const uint8_t PXE_Hell2[];
extern const uint8_t PXE_Hell3[];
extern const uint8_t PXE_Hell4[];
extern const uint8_t PXE_Hell42[];
extern const uint8_t PXE_Island[];
extern const uint8_t PXE_Itoh[];
extern const uint8_t PXE_Jail1[];
extern const uint8_t PXE_Jail2[];
extern const uint8_t PXE_Jenka1[];
extern const uint8_t PXE_Jenka2[];
extern const uint8_t PXE_Kings[];
extern const uint8_t PXE_Little[];
extern const uint8_t PXE_Lounge[];
extern const uint8_t PXE_Malco[];
extern const uint8_t PXE_Mapi[];
extern const uint8_t PXE_MazeA[];
extern const uint8_t PXE_MazeB[];
extern const uint8_t PXE_MazeD[];
extern const uint8_t PXE_MazeH[];
extern const uint8_t PXE_MazeI[];
extern const uint8_t PXE_MazeM[];
extern const uint8_t PXE_MazeO[];
extern const uint8_t PXE_MazeS[];
extern const uint8_t PXE_MazeW[];
extern const uint8_t PXE_MiBox[];
extern const uint8_t PXE_Mimi[];
extern const uint8_t PXE_Momo[];
extern const uint8_t PXE_Oside[];
extern const uint8_t PXE_Ostep[];
extern const uint8_t PXE_Pens1[];
extern const uint8_t PXE_Pens2[];
extern const uint8_t PXE_Pixel[];
extern const uint8_t PXE_Plant[];
extern const uint8_t PXE_Pole[];
extern const uint8_t PXE_Pool[];
extern const uint8_t PXE_Prefa1[];
extern const uint8_t PXE_Prefa2[];
extern const uint8_t PXE_Priso1[];
extern const uint8_t PXE_Priso2[];
extern const uint8_t PXE_Ring1[];
extern const uint8_t PXE_Ring2[];
extern const uint8_t PXE_Ring3[];
extern const uint8_t PXE_River[];
extern const uint8_t PXE_Sand[];
extern const uint8_t PXE_SandE[];
extern const uint8_t PXE_Santa[];
extern const uint8_t PXE_Shelt[];
extern const uint8_t PXE_Start[];
extern const uint8_t PXE_Statue[];
extern const uint8_t PXE_Stream[];
extern const uint8_t PXE_Weed[];
extern const uint8_t PXE_WeedB[];
extern const uint8_t PXE_WeedD[];
extern const uint8_t PXE_WeedS[];

extern const uint8_t z80_xgm[], z80_xgm_end[];
extern const uint8_t stop_xgm;

extern const uint8_t NPC_TABLE[];

extern const uint8_t PAT_MoonTop[];
extern const uint8_t MAP_MoonTop[];
extern const uint8_t PAT_MoonBtm[];
extern const uint8_t MAP_MoonBtm[];
extern const uint8_t PAT_FogTop[];
extern const uint8_t MAP_FogTop[];
extern const uint8_t PAT_FogBtm[];
extern const uint8_t MAP_FogBtm[];
extern const uint8_t PAT_QuakerB[];
extern const uint8_t MAP_QuakerB[];
extern const uint8_t PAT_SndTest[];
extern const uint8_t MAP_SndTest[];

extern const uint8_t PAT_Ill01[];
extern const uint8_t MAP_Ill01[];
extern const uint8_t PAT_Ill02[];
extern const uint8_t MAP_Ill02[];
extern const uint8_t PAT_Ill03[];
extern const uint8_t MAP_Ill03[];
extern const uint8_t PAT_Ill04[];
extern const uint8_t MAP_Ill04[];
extern const uint8_t PAT_Ill05[];
extern const uint8_t MAP_Ill05[];
extern const uint8_t PAT_Ill06[];
extern const uint8_t MAP_Ill06[];
extern const uint8_t PAT_Ill07[];
extern const uint8_t MAP_Ill07[];
extern const uint8_t PAT_Ill08[];
extern const uint8_t MAP_Ill08[];
extern const uint8_t PAT_Ill09[];
extern const uint8_t MAP_Ill09[];
extern const uint8_t PAT_Ill10[];
extern const uint8_t MAP_Ill10[];
extern const uint8_t PAT_Ill11[];
extern const uint8_t MAP_Ill11[];
extern const uint8_t PAT_Ill12[];
extern const uint8_t MAP_Ill12[];

extern const uint8_t PAT_Ill14[];
extern const uint8_t MAP_Ill14[];
extern const uint8_t PAT_Ill15[];
extern const uint8_t MAP_Ill15[];
extern const uint8_t PAT_Ill16[];
extern const uint8_t MAP_Ill16[];
extern const uint8_t PAT_Ill17[];
extern const uint8_t MAP_Ill17[];
extern const uint8_t PAT_Ill18[];
extern const uint8_t MAP_Ill18[];

extern const uint8_t SFX_01[], SFX_01_end[];
extern const uint8_t SFX_02[], SFX_02_end[];
extern const uint8_t SFX_03[], SFX_03_end[];
extern const uint8_t SFX_04[], SFX_04_end[];
extern const uint8_t SFX_05[], SFX_05_end[];
extern const uint8_t SFX_06[], SFX_06_end[];
extern const uint8_t SFX_07[], SFX_07_end[];
extern const uint8_t SFX_08[], SFX_08_end[];
extern const uint8_t SFX_0B[], SFX_0B_end[];
extern const uint8_t SFX_0C[], SFX_0C_end[];
extern const uint8_t SFX_0E[], SFX_0E_end[];
extern const uint8_t SFX_0F[], SFX_0F_end[];
extern const uint8_t SFX_10[], SFX_10_end[];
extern const uint8_t SFX_11[], SFX_11_end[];
extern const uint8_t SFX_12[], SFX_12_end[];
extern const uint8_t SFX_14[], SFX_14_end[];
extern const uint8_t SFX_15[], SFX_15_end[];
extern const uint8_t SFX_16[], SFX_16_end[];
extern const uint8_t SFX_17[], SFX_17_end[];
extern const uint8_t SFX_18[], SFX_18_end[];
extern const uint8_t SFX_19[], SFX_19_end[];
extern const uint8_t SFX_1A[], SFX_1A_end[];
extern const uint8_t SFX_1B[], SFX_1B_end[];
extern const uint8_t SFX_1C[], SFX_1C_end[];
extern const uint8_t SFX_1D[], SFX_1D_end[];
extern const uint8_t SFX_1E[], SFX_1E_end[];
extern const uint8_t SFX_1F[], SFX_1F_end[];
extern const uint8_t SFX_20[], SFX_20_end[];
extern const uint8_t SFX_21[], SFX_21_end[];
extern const uint8_t SFX_22[], SFX_22_end[];
extern const uint8_t SFX_23[], SFX_23_end[];
extern const uint8_t SFX_25[], SFX_25_end[];
extern const uint8_t SFX_26[], SFX_26_end[];
extern const uint8_t SFX_27[], SFX_27_end[];
extern const uint8_t SFX_28[], SFX_28_end[];
extern const uint8_t SFX_2A[], SFX_2A_end[];
extern const uint8_t SFX_2B[], SFX_2B_end[];
extern const uint8_t SFX_2C[], SFX_2C_end[];
extern const uint8_t SFX_2D[], SFX_2D_end[];
extern const uint8_t SFX_2E[], SFX_2E_end[];
extern const uint8_t SFX_2F[], SFX_2F_end[];
extern const uint8_t SFX_30[], SFX_30_end[];
extern const uint8_t SFX_31[], SFX_31_end[];
extern const uint8_t SFX_32[], SFX_32_end[];
extern const uint8_t SFX_33[], SFX_33_end[];
extern const uint8_t SFX_34[], SFX_34_end[];
extern const uint8_t SFX_35[], SFX_35_end[];
extern const uint8_t SFX_36[], SFX_36_end[];
extern const uint8_t SFX_37[], SFX_37_end[];
extern const uint8_t SFX_38[], SFX_38_end[];
extern const uint8_t SFX_39[], SFX_39_end[];
extern const uint8_t SFX_3A[], SFX_3A_end[];
extern const uint8_t SFX_3B[], SFX_3B_end[];
extern const uint8_t SFX_3C[], SFX_3C_end[];
extern const uint8_t SFX_3D[], SFX_3D_end[];
extern const uint8_t SFX_3E[], SFX_3E_end[];
extern const uint8_t SFX_3F[], SFX_3F_end[];
extern const uint8_t SFX_40[], SFX_40_end[];
extern const uint8_t SFX_41[], SFX_41_end[];
extern const uint8_t SFX_46[], SFX_46_end[];
extern const uint8_t SFX_47[], SFX_47_end[];
extern const uint8_t SFX_48[], SFX_48_end[];
extern const uint8_t SFX_64[], SFX_64_end[];
extern const uint8_t SFX_65[], SFX_65_end[];
extern const uint8_t SFX_66[], SFX_66_end[];
extern const uint8_t SFX_67[], SFX_67_end[];
extern const uint8_t SFX_68[], SFX_68_end[];
extern const uint8_t SFX_69[], SFX_69_end[];
extern const uint8_t SFX_6A[], SFX_6A_end[];
extern const uint8_t SFX_6B[], SFX_6B_end[];
extern const uint8_t SFX_6C[], SFX_6C_end[];
extern const uint8_t SFX_6D[], SFX_6D_end[];
extern const uint8_t SFX_6E[], SFX_6E_end[];
extern const uint8_t SFX_6F[], SFX_6F_end[];
extern const uint8_t SFX_70[], SFX_70_end[];
extern const uint8_t SFX_71[], SFX_71_end[];
extern const uint8_t SFX_72[], SFX_72_end[];
extern const uint8_t SFX_73[], SFX_73_end[];
extern const uint8_t SFX_74[], SFX_74_end[];
extern const uint8_t SFX_75[], SFX_75_end[];

extern const uint8_t BGM_Mischievous[];
extern const uint8_t BGM_Safety[];
extern const uint8_t BGM_GameOver[];
extern const uint8_t BGM_Gravity[];
extern const uint8_t BGM_Grasstown[];
extern const uint8_t BGM_Meltdown2[];
extern const uint8_t BGM_EyesOfFlame[];
extern const uint8_t BGM_Gestation[];
extern const uint8_t BGM_Mimiga[];
extern const uint8_t BGM_Fanfare1[];
extern const uint8_t BGM_Balrog[];
extern const uint8_t BGM_Cemetery[];
extern const uint8_t BGM_Plant[];
extern const uint8_t BGM_Pulse[];
extern const uint8_t BGM_Fanfare2[];
extern const uint8_t BGM_Fanfare3[];
extern const uint8_t BGM_Tyrant[];
extern const uint8_t BGM_Run[];
extern const uint8_t BGM_Jenka1[];
extern const uint8_t BGM_LabFight[];
extern const uint8_t BGM_Access[];
extern const uint8_t BGM_Oppression[];
extern const uint8_t BGM_Geothermal[];
extern const uint8_t BGM_CaveStory[];
extern const uint8_t BGM_MoonSong[];
extern const uint8_t BGM_HerosEnd[];
extern const uint8_t BGM_Scorching[];
extern const uint8_t BGM_Quiet[];
extern const uint8_t BGM_LastCave[];
extern const uint8_t BGM_Balcony[];
extern const uint8_t BGM_Charge[];
extern const uint8_t BGM_LastBoss[];
extern const uint8_t BGM_WayBackHome[];
extern const uint8_t BGM_Zombie[];
extern const uint8_t BGM_Breakdown[];
extern const uint8_t BGM_RunningHell[];
extern const uint8_t BGM_Jenka2[];
extern const uint8_t BGM_Waterway[];
extern const uint8_t BGM_SealChamber[];
extern const uint8_t BGM_Toroko[];
extern const uint8_t BGM_White[];
extern const uint8_t BGM_TimeTable[];

extern const uint8_t LS_00[];
extern const uint8_t LS_01[];
extern const uint8_t LS_02[];
extern const uint8_t LS_03[];
extern const uint8_t LS_04[];
extern const uint8_t LS_05[];
extern const uint8_t LS_06[];
extern const uint8_t LS_07[];
extern const uint8_t LS_08[];
extern const uint8_t LS_09[];
extern const uint8_t LS_10[];
extern const uint8_t LS_11[];
extern const uint8_t LS_12[];
extern const uint8_t LS_13[];
extern const uint8_t LS_14[];
extern const uint8_t LS_15[];
extern const uint8_t LS_16[];
extern const uint8_t LS_17[];
extern const uint8_t LS_18[];
extern const uint8_t LS_19[];
extern const uint8_t LS_20[];
extern const uint8_t LS_21[];

/* Language pointer tables */
extern const uint8_t LANGUAGE[4];

extern const uint32_t TSC_GLOB[4];
extern const uint32_t TSC_STAGE[95];

extern const uint32_t BMP_ASCII;
extern const uint32_t BMP_KANJI;

extern const uint32_t STAGE_NAMES;
extern const uint32_t CREDITS_STR;
extern const uint32_t CONFIG_STR;
