extern const uint8_t PXA_Almond[];
extern const uint8_t PXA_Barr[];
extern const uint8_t PXA_Cave[];
extern const uint8_t PXA_Cent[];
extern const uint8_t PXA_EggIn[];
extern const uint8_t PXA_EggX[];
extern const uint8_t PXA_Fall[];
extern const uint8_t PXA_Gard[];
extern const uint8_t PXA_Jail[];
extern const uint8_t PXA_Labo[];
extern const uint8_t PXA_Oside[];
extern const uint8_t PXA_Pens[];
extern const uint8_t PXA_River[];
extern const uint8_t PXA_Sand[];
extern const uint8_t PXA_Store[];
extern const uint8_t PXA_Weed[];

extern const uint8_t PXA_Mimi[];
extern const uint8_t PXM_Barr[];
extern const uint8_t PXM_Cemet[];
extern const uint8_t PXM_e_Ceme[];
extern const uint8_t PXM_MiBox[];
extern const uint8_t PXM_Mimi[];
extern const uint8_t PXM_Plant[];
extern const uint8_t PXM_Pool[];
extern const uint8_t PXA_Eggs[];
extern const uint8_t PXA_Eggs2[];
extern const uint8_t PXM_Eggs[];
extern const uint8_t PXM_Eggs2[];
extern const uint8_t PXA_Maze[];
extern const uint8_t PXM_e_Maze[];
extern const uint8_t PXM_MazeB[];
extern const uint8_t PXM_MazeD[];
extern const uint8_t PXM_MazeH[];
extern const uint8_t PXM_MazeI[];
extern const uint8_t PXM_MazeO[];
extern const uint8_t PXM_MazeS[];
extern const uint8_t PXM_MazeW[];
extern const uint8_t PXA_MazeM[];
extern const uint8_t PXM_MazeM[];
extern const uint8_t PXA_Blcny[];
extern const uint8_t PXM_e_Blcn[];
extern const uint8_t PXM_Blcny1[];
extern const uint8_t PXM_Blcny2[];
extern const uint8_t PXA_Kings[];
extern const uint8_t PXM_Kings[];
extern const uint8_t PXM_Ring1[];
extern const uint8_t PXM_Ostep[];
extern const uint8_t PXA_Ring2[];
extern const uint8_t PXM_Ring2[];
extern const uint8_t PXA_Ring3[];
extern const uint8_t PXM_Ring3[];
extern const uint8_t PXA_Hell[];
extern const uint8_t PXM_Hell1[];
extern const uint8_t PXM_Hell2[];
extern const uint8_t PXM_Hell3[];
extern const uint8_t PXM_Hell4[];
extern const uint8_t PXM_Hell42[];
extern const uint8_t PXM_Ballo1[];
extern const uint8_t PXM_Ballo2[];
extern const uint8_t PXA_Statue[];
extern const uint8_t PXM_Statue[];

extern const uint8_t PXM_Almond[];
extern const uint8_t PXM_Cave[];
extern const uint8_t PXM_Cent[];
extern const uint8_t PXM_CentW[];
extern const uint8_t PXM_Chako[];
extern const uint8_t PXM_Clock[];
extern const uint8_t PXM_Comu[];
extern const uint8_t PXM_Cthu[];
extern const uint8_t PXM_Cthu2[];
extern const uint8_t PXM_Curly[];
extern const uint8_t PXM_CurlyS[];
extern const uint8_t PXM_Dark[];
extern const uint8_t PXM_Drain[];
extern const uint8_t PXM_e_Jenk[];
extern const uint8_t PXM_e_Labo[];
extern const uint8_t PXM_e_Malc[];
extern const uint8_t PXM_e_Sky[];
extern const uint8_t PXM_EgEnd1[];
extern const uint8_t PXM_EgEnd2[];
extern const uint8_t PXM_Egg1[];
extern const uint8_t PXM_Egg6[];
extern const uint8_t PXM_EggR[];
extern const uint8_t PXM_EggR2[];
extern const uint8_t PXM_EggX[];
extern const uint8_t PXM_EggX2[];
extern const uint8_t PXM_Fall[];
extern const uint8_t PXM_Frog[];
extern const uint8_t PXM_Gard[];
extern const uint8_t PXM_Itoh[];
extern const uint8_t PXM_Island[];
extern const uint8_t PXM_Jail1[];
extern const uint8_t PXM_Jail2[];
extern const uint8_t PXM_Jenka1[];
extern const uint8_t PXM_Jenka2[];
extern const uint8_t PXM_Little[];
extern const uint8_t PXM_Lounge[];
extern const uint8_t PXM_Malco[];
extern const uint8_t PXM_Mapi[];
extern const uint8_t PXM_MazeA[];
extern const uint8_t PXM_Momo[];
extern const uint8_t PXM_Oside[];
extern const uint8_t PXM_Pens1[];
extern const uint8_t PXM_Pens2[];
extern const uint8_t PXM_Pixel[];
extern const uint8_t PXM_Pole[];
extern const uint8_t PXM_Prefa1[];
extern const uint8_t PXM_Prefa2[];
extern const uint8_t PXM_Priso1[];
extern const uint8_t PXM_Priso2[];
extern const uint8_t PXM_River[];
extern const uint8_t PXM_Sand[];
extern const uint8_t PXM_SandE[];
extern const uint8_t PXM_Santa[];
extern const uint8_t PXM_Shelt[];
extern const uint8_t PXM_Start[];
extern const uint8_t PXM_Stream[];
extern const uint8_t PXM_Weed[];
extern const uint8_t PXM_WeedB[];
extern const uint8_t PXM_WeedD[];
extern const uint8_t PXM_WeedS[];

extern const uint8_t PXE_Almond[];
extern const uint8_t PXE_Ballo1[];
extern const uint8_t PXE_Ballo2[];
extern const uint8_t PXE_Barr[];
extern const uint8_t PXE_Blcny1[];
extern const uint8_t PXE_Blcny2[];
extern const uint8_t PXE_Cave[];
extern const uint8_t PXE_Cemet[];
extern const uint8_t PXE_Cent[];
extern const uint8_t PXE_CentW[];
extern const uint8_t PXE_Chako[];
extern const uint8_t PXE_Clock[];
extern const uint8_t PXE_Comu[];
extern const uint8_t PXE_Cthu[];
extern const uint8_t PXE_Cthu2[];
extern const uint8_t PXE_Curly[];
extern const uint8_t PXE_CurlyS[];
extern const uint8_t PXE_Dark[];
extern const uint8_t PXE_Drain[];
extern const uint8_t PXE_e_Blcn[];
extern const uint8_t PXE_e_Ceme[];
extern const uint8_t PXE_e_Jenk[];
extern const uint8_t PXE_e_Labo[];
extern const uint8_t PXE_e_Malc[];
extern const uint8_t PXE_e_Maze[];
extern const uint8_t PXE_e_Sky[];
extern const uint8_t PXE_EgEnd1[];
extern const uint8_t PXE_EgEnd2[];
extern const uint8_t PXE_Egg1[];
extern const uint8_t PXE_Egg6[];
extern const uint8_t PXE_EggR[];
extern const uint8_t PXE_EggR2[];
extern const uint8_t PXE_Eggs[];
extern const uint8_t PXE_Eggs2[];
extern const uint8_t PXE_EggX[];
extern const uint8_t PXE_EggX2[];
extern const uint8_t PXE_Fall[];
extern const uint8_t PXE_Frog[];
extern const uint8_t PXE_Gard[];
extern const uint8_t PXE_Hell1[];
extern const uint8_t PXE_Hell2[];
extern const uint8_t PXE_Hell3[];
extern const uint8_t PXE_Hell4[];
extern const uint8_t PXE_Hell42[];
extern const uint8_t PXE_Island[];
extern const uint8_t PXE_Itoh[];
extern const uint8_t PXE_Jail1[];
extern const uint8_t PXE_Jail2[];
extern const uint8_t PXE_Jenka1[];
extern const uint8_t PXE_Jenka2[];
extern const uint8_t PXE_Kings[];
extern const uint8_t PXE_Little[];
extern const uint8_t PXE_Lounge[];
extern const uint8_t PXE_Malco[];
extern const uint8_t PXE_Mapi[];
extern const uint8_t PXE_MazeA[];
extern const uint8_t PXE_MazeB[];
extern const uint8_t PXE_MazeD[];
extern const uint8_t PXE_MazeH[];
extern const uint8_t PXE_MazeI[];
extern const uint8_t PXE_MazeM[];
extern const uint8_t PXE_MazeO[];
extern const uint8_t PXE_MazeS[];
extern const uint8_t PXE_MazeW[];
extern const uint8_t PXE_MiBox[];
extern const uint8_t PXE_Mimi[];
extern const uint8_t PXE_Momo[];
extern const uint8_t PXE_Oside[];
extern const uint8_t PXE_Ostep[];
extern const uint8_t PXE_Pens1[];
extern const uint8_t PXE_Pens2[];
extern const uint8_t PXE_Pixel[];
extern const uint8_t PXE_Plant[];
extern const uint8_t PXE_Pole[];
extern const uint8_t PXE_Pool[];
extern const uint8_t PXE_Prefa1[];
extern const uint8_t PXE_Prefa2[];
extern const uint8_t PXE_Priso1[];
extern const uint8_t PXE_Priso2[];
extern const uint8_t PXE_Ring1[];
extern const uint8_t PXE_Ring2[];
extern const uint8_t PXE_Ring3[];
extern const uint8_t PXE_River[];
extern const uint8_t PXE_Sand[];
extern const uint8_t PXE_SandE[];
extern const uint8_t PXE_Santa[];
extern const uint8_t PXE_Shelt[];
extern const uint8_t PXE_Start[];
extern const uint8_t PXE_Statue[];
extern const uint8_t PXE_Stream[];
extern const uint8_t PXE_Weed[];
extern const uint8_t PXE_WeedB[];
extern const uint8_t PXE_WeedD[];
extern const uint8_t PXE_WeedS[];

extern const uint8_t TSC_ArmsItem[];
extern const uint8_t TSC_Head[];
extern const uint8_t TSC_StageSelect[];
extern const uint8_t TSC_Credits[];
extern const uint8_t TSC_Almond[];
extern const uint8_t TSC_Ballo1[];
extern const uint8_t TSC_Ballo2[];
extern const uint8_t TSC_Barr[];
extern const uint8_t TSC_Blcny1[];
extern const uint8_t TSC_Blcny2[];
extern const uint8_t TSC_Cave[];
extern const uint8_t TSC_Cemet[];
extern const uint8_t TSC_Cent[];
extern const uint8_t TSC_CentW[];
extern const uint8_t TSC_Chako[];
extern const uint8_t TSC_Clock[];
extern const uint8_t TSC_Comu[];
extern const uint8_t TSC_Cthu[];
extern const uint8_t TSC_Cthu2[];
extern const uint8_t TSC_Curly[];
extern const uint8_t TSC_CurlyS[];
extern const uint8_t TSC_Dark[];
extern const uint8_t TSC_Drain[];
extern const uint8_t TSC_e_Blcn[];
extern const uint8_t TSC_e_Ceme[];
extern const uint8_t TSC_e_Jenk[];
extern const uint8_t TSC_e_Labo[];
extern const uint8_t TSC_e_Malc[];
extern const uint8_t TSC_e_Maze[];
extern const uint8_t TSC_e_Sky[];
extern const uint8_t TSC_EgEnd1[];
extern const uint8_t TSC_EgEnd2[];
extern const uint8_t TSC_Egg1[];
extern const uint8_t TSC_Egg6[];
extern const uint8_t TSC_EggR[];
extern const uint8_t TSC_EggR2[];
extern const uint8_t TSC_Eggs[];
extern const uint8_t TSC_Eggs2[];
extern const uint8_t TSC_EggX[];
extern const uint8_t TSC_EggX2[];
extern const uint8_t TSC_Fall[];
extern const uint8_t TSC_Frog[];
extern const uint8_t TSC_Gard[];
extern const uint8_t TSC_Hell1[];
extern const uint8_t TSC_Hell2[];
extern const uint8_t TSC_Hell3[];
extern const uint8_t TSC_Hell4[];
extern const uint8_t TSC_Hell42[];
extern const uint8_t TSC_Island[];
extern const uint8_t TSC_Itoh[];
extern const uint8_t TSC_Jail1[];
extern const uint8_t TSC_Jail2[];
extern const uint8_t TSC_Jenka1[];
extern const uint8_t TSC_Jenka2[];
extern const uint8_t TSC_Kings[];
extern const uint8_t TSC_Little[];
extern const uint8_t TSC_Lounge[];
extern const uint8_t TSC_Malco[];
extern const uint8_t TSC_Mapi[];
extern const uint8_t TSC_MazeA[];
extern const uint8_t TSC_MazeB[];
extern const uint8_t TSC_MazeD[];
extern const uint8_t TSC_MazeH[];
extern const uint8_t TSC_MazeI[];
extern const uint8_t TSC_MazeM[];
extern const uint8_t TSC_MazeO[];
extern const uint8_t TSC_MazeS[];
extern const uint8_t TSC_MazeW[];
extern const uint8_t TSC_MiBox[];
extern const uint8_t TSC_Mimi[];
extern const uint8_t TSC_Momo[];
extern const uint8_t TSC_Oside[];
extern const uint8_t TSC_Ostep[];
extern const uint8_t TSC_Pens1[];
extern const uint8_t TSC_Pens2[];
extern const uint8_t TSC_Pixel[];
extern const uint8_t TSC_Plant[];
extern const uint8_t TSC_Pole[];
extern const uint8_t TSC_Pool[];
extern const uint8_t TSC_Prefa1[];
extern const uint8_t TSC_Prefa2[];
extern const uint8_t TSC_Priso1[];
extern const uint8_t TSC_Priso2[];
extern const uint8_t TSC_Ring1[];
extern const uint8_t TSC_Ring2[];
extern const uint8_t TSC_Ring3[];
extern const uint8_t TSC_River[];
extern const uint8_t TSC_Sand[];
extern const uint8_t TSC_SandE[];
extern const uint8_t TSC_Santa[];
extern const uint8_t TSC_Shelt[];
extern const uint8_t TSC_Start[];
extern const uint8_t TSC_Statue[];
extern const uint8_t TSC_Stream[];
extern const uint8_t TSC_Weed[];
extern const uint8_t TSC_WeedB[];
extern const uint8_t TSC_WeedD[];
extern const uint8_t TSC_WeedS[];

extern const uint8_t JTSC_ArmsItem[];
extern const uint8_t JTSC_Head[];
extern const uint8_t JTSC_StageSelect[];
extern const uint8_t JTSC_Credits[];
extern const uint8_t JTSC_Almond[];
extern const uint8_t JTSC_Ballo1[];
extern const uint8_t JTSC_Ballo2[];
extern const uint8_t JTSC_Barr[];
extern const uint8_t JTSC_Blcny1[];
extern const uint8_t JTSC_Blcny2[];
extern const uint8_t JTSC_Cave[];
extern const uint8_t JTSC_Cemet[];
extern const uint8_t JTSC_Cent[];
extern const uint8_t JTSC_CentW[];
extern const uint8_t JTSC_Chako[];
extern const uint8_t JTSC_Clock[];
extern const uint8_t JTSC_Comu[];
extern const uint8_t JTSC_Cthu[];
extern const uint8_t JTSC_Cthu2[];
extern const uint8_t JTSC_Curly[];
extern const uint8_t JTSC_CurlyS[];
extern const uint8_t JTSC_Dark[];
extern const uint8_t JTSC_Drain[];
extern const uint8_t JTSC_e_Blcn[];
extern const uint8_t JTSC_e_Ceme[];
extern const uint8_t JTSC_e_Jenk[];
extern const uint8_t JTSC_e_Labo[];
extern const uint8_t JTSC_e_Malc[];
extern const uint8_t JTSC_e_Maze[];
extern const uint8_t JTSC_e_Sky[];
extern const uint8_t JTSC_EgEnd1[];
extern const uint8_t JTSC_EgEnd2[];
extern const uint8_t JTSC_Egg1[];
extern const uint8_t JTSC_Egg6[];
extern const uint8_t JTSC_EggR[];
extern const uint8_t JTSC_EggR2[];
extern const uint8_t JTSC_Eggs[];
extern const uint8_t JTSC_Eggs2[];
extern const uint8_t JTSC_EggX[];
extern const uint8_t JTSC_EggX2[];
extern const uint8_t JTSC_Fall[];
extern const uint8_t JTSC_Frog[];
extern const uint8_t JTSC_Gard[];
extern const uint8_t JTSC_Hell1[];
extern const uint8_t JTSC_Hell2[];
extern const uint8_t JTSC_Hell3[];
extern const uint8_t JTSC_Hell4[];
extern const uint8_t JTSC_Hell42[];
extern const uint8_t JTSC_Island[];
extern const uint8_t JTSC_Itoh[];
extern const uint8_t JTSC_Jail1[];
extern const uint8_t JTSC_Jail2[];
extern const uint8_t JTSC_Jenka1[];
extern const uint8_t JTSC_Jenka2[];
extern const uint8_t JTSC_Kings[];
extern const uint8_t JTSC_Little[];
extern const uint8_t JTSC_Lounge[];
extern const uint8_t JTSC_Malco[];
extern const uint8_t JTSC_Mapi[];
extern const uint8_t JTSC_MazeA[];
extern const uint8_t JTSC_MazeB[];
extern const uint8_t JTSC_MazeD[];
extern const uint8_t JTSC_MazeH[];
extern const uint8_t JTSC_MazeI[];
extern const uint8_t JTSC_MazeM[];
extern const uint8_t JTSC_MazeO[];
extern const uint8_t JTSC_MazeS[];
extern const uint8_t JTSC_MazeW[];
extern const uint8_t JTSC_MiBox[];
extern const uint8_t JTSC_Mimi[];
extern const uint8_t JTSC_Momo[];
extern const uint8_t JTSC_Oside[];
extern const uint8_t JTSC_Ostep[];
extern const uint8_t JTSC_Pens1[];
extern const uint8_t JTSC_Pens2[];
extern const uint8_t JTSC_Pixel[];
extern const uint8_t JTSC_Plant[];
extern const uint8_t JTSC_Pole[];
extern const uint8_t JTSC_Pool[];
extern const uint8_t JTSC_Prefa1[];
extern const uint8_t JTSC_Prefa2[];
extern const uint8_t JTSC_Priso1[];
extern const uint8_t JTSC_Priso2[];
extern const uint8_t JTSC_Ring1[];
extern const uint8_t JTSC_Ring2[];
extern const uint8_t JTSC_Ring3[];
extern const uint8_t JTSC_River[];
extern const uint8_t JTSC_Sand[];
extern const uint8_t JTSC_SandE[];
extern const uint8_t JTSC_Santa[];
extern const uint8_t JTSC_Shelt[];
extern const uint8_t JTSC_Start[];
extern const uint8_t JTSC_Statue[];
extern const uint8_t JTSC_Stream[];
extern const uint8_t JTSC_Weed[];
extern const uint8_t JTSC_WeedB[];
extern const uint8_t JTSC_WeedD[];
extern const uint8_t JTSC_WeedS[];

extern const uint8_t STSC_ArmsItem[];
extern const uint8_t STSC_Head[];
extern const uint8_t STSC_StageSelect[];
extern const uint8_t STSC_Credits[];
extern const uint8_t STSC_Almond[];
extern const uint8_t STSC_Ballo1[];
extern const uint8_t STSC_Ballo2[];
extern const uint8_t STSC_Barr[];
extern const uint8_t STSC_Blcny1[];
extern const uint8_t STSC_Blcny2[];
extern const uint8_t STSC_Cave[];
extern const uint8_t STSC_Cemet[];
extern const uint8_t STSC_Cent[];
extern const uint8_t STSC_CentW[];
extern const uint8_t STSC_Chako[];
extern const uint8_t STSC_Clock[];
extern const uint8_t STSC_Comu[];
extern const uint8_t STSC_Cthu[];
extern const uint8_t STSC_Cthu2[];
extern const uint8_t STSC_Curly[];
extern const uint8_t STSC_CurlyS[];
extern const uint8_t STSC_Dark[];
extern const uint8_t STSC_Drain[];
extern const uint8_t STSC_e_Blcn[];
extern const uint8_t STSC_e_Ceme[];
extern const uint8_t STSC_e_Jenk[];
extern const uint8_t STSC_e_Labo[];
extern const uint8_t STSC_e_Malc[];
extern const uint8_t STSC_e_Maze[];
extern const uint8_t STSC_e_Sky[];
extern const uint8_t STSC_EgEnd1[];
extern const uint8_t STSC_EgEnd2[];
extern const uint8_t STSC_Egg1[];
extern const uint8_t STSC_Egg6[];
extern const uint8_t STSC_EggR[];
extern const uint8_t STSC_EggR2[];
extern const uint8_t STSC_Eggs[];
extern const uint8_t STSC_Eggs2[];
extern const uint8_t STSC_EggX[];
extern const uint8_t STSC_EggX2[];
extern const uint8_t STSC_Fall[];
extern const uint8_t STSC_Frog[];
extern const uint8_t STSC_Gard[];
extern const uint8_t STSC_Hell1[];
extern const uint8_t STSC_Hell2[];
extern const uint8_t STSC_Hell3[];
extern const uint8_t STSC_Hell4[];
extern const uint8_t STSC_Hell42[];
extern const uint8_t STSC_Island[];
extern const uint8_t STSC_Itoh[];
extern const uint8_t STSC_Jail1[];
extern const uint8_t STSC_Jail2[];
extern const uint8_t STSC_Jenka1[];
extern const uint8_t STSC_Jenka2[];
extern const uint8_t STSC_Kings[];
extern const uint8_t STSC_Little[];
extern const uint8_t STSC_Lounge[];
extern const uint8_t STSC_Malco[];
extern const uint8_t STSC_Mapi[];
extern const uint8_t STSC_MazeA[];
extern const uint8_t STSC_MazeB[];
extern const uint8_t STSC_MazeD[];
extern const uint8_t STSC_MazeH[];
extern const uint8_t STSC_MazeI[];
extern const uint8_t STSC_MazeM[];
extern const uint8_t STSC_MazeO[];
extern const uint8_t STSC_MazeS[];
extern const uint8_t STSC_MazeW[];
extern const uint8_t STSC_MiBox[];
extern const uint8_t STSC_Mimi[];
extern const uint8_t STSC_Momo[];
extern const uint8_t STSC_Oside[];
extern const uint8_t STSC_Ostep[];
extern const uint8_t STSC_Pens1[];
extern const uint8_t STSC_Pens2[];
extern const uint8_t STSC_Pixel[];
extern const uint8_t STSC_Plant[];
extern const uint8_t STSC_Pole[];
extern const uint8_t STSC_Pool[];
extern const uint8_t STSC_Prefa1[];
extern const uint8_t STSC_Prefa2[];
extern const uint8_t STSC_Priso1[];
extern const uint8_t STSC_Priso2[];
extern const uint8_t STSC_Ring1[];
extern const uint8_t STSC_Ring2[];
extern const uint8_t STSC_Ring3[];
extern const uint8_t STSC_River[];
extern const uint8_t STSC_Sand[];
extern const uint8_t STSC_SandE[];
extern const uint8_t STSC_Santa[];
extern const uint8_t STSC_Shelt[];
extern const uint8_t STSC_Start[];
extern const uint8_t STSC_Statue[];
extern const uint8_t STSC_Stream[];
extern const uint8_t STSC_Weed[];
extern const uint8_t STSC_WeedB[];
extern const uint8_t STSC_WeedD[];
extern const uint8_t STSC_WeedS[];

extern const uint8_t PTSC_ArmsItem[];
extern const uint8_t PTSC_Head[];
extern const uint8_t PTSC_StageSelect[];
extern const uint8_t PTSC_Credits[];
extern const uint8_t PTSC_Almond[];
extern const uint8_t PTSC_Ballo1[];
extern const uint8_t PTSC_Ballo2[];
extern const uint8_t PTSC_Barr[];
extern const uint8_t PTSC_Blcny1[];
extern const uint8_t PTSC_Blcny2[];
extern const uint8_t PTSC_Cave[];
extern const uint8_t PTSC_Cemet[];
extern const uint8_t PTSC_Cent[];
extern const uint8_t PTSC_CentW[];
extern const uint8_t PTSC_Chako[];
extern const uint8_t PTSC_Clock[];
extern const uint8_t PTSC_Comu[];
extern const uint8_t PTSC_Cthu[];
extern const uint8_t PTSC_Cthu2[];
extern const uint8_t PTSC_Curly[];
extern const uint8_t PTSC_CurlyS[];
extern const uint8_t PTSC_Dark[];
extern const uint8_t PTSC_Drain[];
extern const uint8_t PTSC_e_Blcn[];
extern const uint8_t PTSC_e_Ceme[];
extern const uint8_t PTSC_e_Jenk[];
extern const uint8_t PTSC_e_Labo[];
extern const uint8_t PTSC_e_Malc[];
extern const uint8_t PTSC_e_Maze[];
extern const uint8_t PTSC_e_Sky[];
extern const uint8_t PTSC_EgEnd1[];
extern const uint8_t PTSC_EgEnd2[];
extern const uint8_t PTSC_Egg1[];
extern const uint8_t PTSC_Egg6[];
extern const uint8_t PTSC_EggR[];
extern const uint8_t PTSC_EggR2[];
extern const uint8_t PTSC_Eggs[];
extern const uint8_t PTSC_Eggs2[];
extern const uint8_t PTSC_EggX[];
extern const uint8_t PTSC_EggX2[];
extern const uint8_t PTSC_Fall[];
extern const uint8_t PTSC_Frog[];
extern const uint8_t PTSC_Gard[];
extern const uint8_t PTSC_Hell1[];
extern const uint8_t PTSC_Hell2[];
extern const uint8_t PTSC_Hell3[];
extern const uint8_t PTSC_Hell4[];
extern const uint8_t PTSC_Hell42[];
extern const uint8_t PTSC_Island[];
extern const uint8_t PTSC_Itoh[];
extern const uint8_t PTSC_Jail1[];
extern const uint8_t PTSC_Jail2[];
extern const uint8_t PTSC_Jenka1[];
extern const uint8_t PTSC_Jenka2[];
extern const uint8_t PTSC_Kings[];
extern const uint8_t PTSC_Little[];
extern const uint8_t PTSC_Lounge[];
extern const uint8_t PTSC_Malco[];
extern const uint8_t PTSC_Mapi[];
extern const uint8_t PTSC_MazeA[];
extern const uint8_t PTSC_MazeB[];
extern const uint8_t PTSC_MazeD[];
extern const uint8_t PTSC_MazeH[];
extern const uint8_t PTSC_MazeI[];
extern const uint8_t PTSC_MazeM[];
extern const uint8_t PTSC_MazeO[];
extern const uint8_t PTSC_MazeS[];
extern const uint8_t PTSC_MazeW[];
extern const uint8_t PTSC_MiBox[];
extern const uint8_t PTSC_Mimi[];
extern const uint8_t PTSC_Momo[];
extern const uint8_t PTSC_Oside[];
extern const uint8_t PTSC_Ostep[];
extern const uint8_t PTSC_Pens1[];
extern const uint8_t PTSC_Pens2[];
extern const uint8_t PTSC_Pixel[];
extern const uint8_t PTSC_Plant[];
extern const uint8_t PTSC_Pole[];
extern const uint8_t PTSC_Pool[];
extern const uint8_t PTSC_Prefa1[];
extern const uint8_t PTSC_Prefa2[];
extern const uint8_t PTSC_Priso1[];
extern const uint8_t PTSC_Priso2[];
extern const uint8_t PTSC_Ring1[];
extern const uint8_t PTSC_Ring2[];
extern const uint8_t PTSC_Ring3[];
extern const uint8_t PTSC_River[];
extern const uint8_t PTSC_Sand[];
extern const uint8_t PTSC_SandE[];
extern const uint8_t PTSC_Santa[];
extern const uint8_t PTSC_Shelt[];
extern const uint8_t PTSC_Start[];
extern const uint8_t PTSC_Statue[];
extern const uint8_t PTSC_Stream[];
extern const uint8_t PTSC_Weed[];
extern const uint8_t PTSC_WeedB[];
extern const uint8_t PTSC_WeedD[];
extern const uint8_t PTSC_WeedS[];

extern const uint8_t FTSC_ArmsItem[];
extern const uint8_t FTSC_Head[];
extern const uint8_t FTSC_StageSelect[];
extern const uint8_t FTSC_Credits[];
extern const uint8_t FTSC_Almond[];
extern const uint8_t FTSC_Ballo1[];
extern const uint8_t FTSC_Ballo2[];
extern const uint8_t FTSC_Barr[];
extern const uint8_t FTSC_Blcny1[];
extern const uint8_t FTSC_Blcny2[];
extern const uint8_t FTSC_Cave[];
extern const uint8_t FTSC_Cemet[];
extern const uint8_t FTSC_Cent[];
extern const uint8_t FTSC_CentW[];
extern const uint8_t FTSC_Chako[];
extern const uint8_t FTSC_Clock[];
extern const uint8_t FTSC_Comu[];
extern const uint8_t FTSC_Cthu[];
extern const uint8_t FTSC_Cthu2[];
extern const uint8_t FTSC_Curly[];
extern const uint8_t FTSC_CurlyS[];
extern const uint8_t FTSC_Dark[];
extern const uint8_t FTSC_Drain[];
extern const uint8_t FTSC_e_Blcn[];
extern const uint8_t FTSC_e_Ceme[];
extern const uint8_t FTSC_e_Jenk[];
extern const uint8_t FTSC_e_Labo[];
extern const uint8_t FTSC_e_Malc[];
extern const uint8_t FTSC_e_Maze[];
extern const uint8_t FTSC_e_Sky[];
extern const uint8_t FTSC_EgEnd1[];
extern const uint8_t FTSC_EgEnd2[];
extern const uint8_t FTSC_Egg1[];
extern const uint8_t FTSC_Egg6[];
extern const uint8_t FTSC_EggR[];
extern const uint8_t FTSC_EggR2[];
extern const uint8_t FTSC_Eggs[];
extern const uint8_t FTSC_Eggs2[];
extern const uint8_t FTSC_EggX[];
extern const uint8_t FTSC_EggX2[];
extern const uint8_t FTSC_Fall[];
extern const uint8_t FTSC_Frog[];
extern const uint8_t FTSC_Gard[];
extern const uint8_t FTSC_Hell1[];
extern const uint8_t FTSC_Hell2[];
extern const uint8_t FTSC_Hell3[];
extern const uint8_t FTSC_Hell4[];
extern const uint8_t FTSC_Hell42[];
extern const uint8_t FTSC_Island[];
extern const uint8_t FTSC_Itoh[];
extern const uint8_t FTSC_Jail1[];
extern const uint8_t FTSC_Jail2[];
extern const uint8_t FTSC_Jenka1[];
extern const uint8_t FTSC_Jenka2[];
extern const uint8_t FTSC_Kings[];
extern const uint8_t FTSC_Little[];
extern const uint8_t FTSC_Lounge[];
extern const uint8_t FTSC_Malco[];
extern const uint8_t FTSC_Mapi[];
extern const uint8_t FTSC_MazeA[];
extern const uint8_t FTSC_MazeB[];
extern const uint8_t FTSC_MazeD[];
extern const uint8_t FTSC_MazeH[];
extern const uint8_t FTSC_MazeI[];
extern const uint8_t FTSC_MazeM[];
extern const uint8_t FTSC_MazeO[];
extern const uint8_t FTSC_MazeS[];
extern const uint8_t FTSC_MazeW[];
extern const uint8_t FTSC_MiBox[];
extern const uint8_t FTSC_Mimi[];
extern const uint8_t FTSC_Momo[];
extern const uint8_t FTSC_Oside[];
extern const uint8_t FTSC_Ostep[];
extern const uint8_t FTSC_Pens1[];
extern const uint8_t FTSC_Pens2[];
extern const uint8_t FTSC_Pixel[];
extern const uint8_t FTSC_Plant[];
extern const uint8_t FTSC_Pole[];
extern const uint8_t FTSC_Pool[];
extern const uint8_t FTSC_Prefa1[];
extern const uint8_t FTSC_Prefa2[];
extern const uint8_t FTSC_Priso1[];
extern const uint8_t FTSC_Priso2[];
extern const uint8_t FTSC_Ring1[];
extern const uint8_t FTSC_Ring2[];
extern const uint8_t FTSC_Ring3[];
extern const uint8_t FTSC_River[];
extern const uint8_t FTSC_Sand[];
extern const uint8_t FTSC_SandE[];
extern const uint8_t FTSC_Santa[];
extern const uint8_t FTSC_Shelt[];
extern const uint8_t FTSC_Start[];
extern const uint8_t FTSC_Statue[];
extern const uint8_t FTSC_Stream[];
extern const uint8_t FTSC_Weed[];
extern const uint8_t FTSC_WeedB[];
extern const uint8_t FTSC_WeedD[];
extern const uint8_t FTSC_WeedS[];

extern const uint8_t ITSC_ArmsItem[];
extern const uint8_t ITSC_Head[];
extern const uint8_t ITSC_StageSelect[];
extern const uint8_t ITSC_Credits[];
extern const uint8_t ITSC_Almond[];
extern const uint8_t ITSC_Ballo1[];
extern const uint8_t ITSC_Ballo2[];
extern const uint8_t ITSC_Barr[];
extern const uint8_t ITSC_Blcny1[];
extern const uint8_t ITSC_Blcny2[];
extern const uint8_t ITSC_Cave[];
extern const uint8_t ITSC_Cemet[];
extern const uint8_t ITSC_Cent[];
extern const uint8_t ITSC_CentW[];
extern const uint8_t ITSC_Chako[];
extern const uint8_t ITSC_Clock[];
extern const uint8_t ITSC_Comu[];
extern const uint8_t ITSC_Cthu[];
extern const uint8_t ITSC_Cthu2[];
extern const uint8_t ITSC_Curly[];
extern const uint8_t ITSC_CurlyS[];
extern const uint8_t ITSC_Dark[];
extern const uint8_t ITSC_Drain[];
extern const uint8_t ITSC_e_Blcn[];
extern const uint8_t ITSC_e_Ceme[];
extern const uint8_t ITSC_e_Jenk[];
extern const uint8_t ITSC_e_Labo[];
extern const uint8_t ITSC_e_Malc[];
extern const uint8_t ITSC_e_Maze[];
extern const uint8_t ITSC_e_Sky[];
extern const uint8_t ITSC_EgEnd1[];
extern const uint8_t ITSC_EgEnd2[];
extern const uint8_t ITSC_Egg1[];
extern const uint8_t ITSC_Egg6[];
extern const uint8_t ITSC_EggR[];
extern const uint8_t ITSC_EggR2[];
extern const uint8_t ITSC_Eggs[];
extern const uint8_t ITSC_Eggs2[];
extern const uint8_t ITSC_EggX[];
extern const uint8_t ITSC_EggX2[];
extern const uint8_t ITSC_Fall[];
extern const uint8_t ITSC_Frog[];
extern const uint8_t ITSC_Gard[];
extern const uint8_t ITSC_Hell1[];
extern const uint8_t ITSC_Hell2[];
extern const uint8_t ITSC_Hell3[];
extern const uint8_t ITSC_Hell4[];
extern const uint8_t ITSC_Hell42[];
extern const uint8_t ITSC_Island[];
extern const uint8_t ITSC_Itoh[];
extern const uint8_t ITSC_Jail1[];
extern const uint8_t ITSC_Jail2[];
extern const uint8_t ITSC_Jenka1[];
extern const uint8_t ITSC_Jenka2[];
extern const uint8_t ITSC_Kings[];
extern const uint8_t ITSC_Little[];
extern const uint8_t ITSC_Lounge[];
extern const uint8_t ITSC_Malco[];
extern const uint8_t ITSC_Mapi[];
extern const uint8_t ITSC_MazeA[];
extern const uint8_t ITSC_MazeB[];
extern const uint8_t ITSC_MazeD[];
extern const uint8_t ITSC_MazeH[];
extern const uint8_t ITSC_MazeI[];
extern const uint8_t ITSC_MazeM[];
extern const uint8_t ITSC_MazeO[];
extern const uint8_t ITSC_MazeS[];
extern const uint8_t ITSC_MazeW[];
extern const uint8_t ITSC_MiBox[];
extern const uint8_t ITSC_Mimi[];
extern const uint8_t ITSC_Momo[];
extern const uint8_t ITSC_Oside[];
extern const uint8_t ITSC_Ostep[];
extern const uint8_t ITSC_Pens1[];
extern const uint8_t ITSC_Pens2[];
extern const uint8_t ITSC_Pixel[];
extern const uint8_t ITSC_Plant[];
extern const uint8_t ITSC_Pole[];
extern const uint8_t ITSC_Pool[];
extern const uint8_t ITSC_Prefa1[];
extern const uint8_t ITSC_Prefa2[];
extern const uint8_t ITSC_Priso1[];
extern const uint8_t ITSC_Priso2[];
extern const uint8_t ITSC_Ring1[];
extern const uint8_t ITSC_Ring2[];
extern const uint8_t ITSC_Ring3[];
extern const uint8_t ITSC_River[];
extern const uint8_t ITSC_Sand[];
extern const uint8_t ITSC_SandE[];
extern const uint8_t ITSC_Santa[];
extern const uint8_t ITSC_Shelt[];
extern const uint8_t ITSC_Start[];
extern const uint8_t ITSC_Statue[];
extern const uint8_t ITSC_Stream[];
extern const uint8_t ITSC_Weed[];
extern const uint8_t ITSC_WeedB[];
extern const uint8_t ITSC_WeedD[];
extern const uint8_t ITSC_WeedS[];

extern const uint8_t GTSC_ArmsItem[];
extern const uint8_t GTSC_Head[];
extern const uint8_t GTSC_StageSelect[];
extern const uint8_t GTSC_Credits[];
extern const uint8_t GTSC_Almond[];
extern const uint8_t GTSC_Ballo1[];
extern const uint8_t GTSC_Ballo2[];
extern const uint8_t GTSC_Barr[];
extern const uint8_t GTSC_Blcny1[];
extern const uint8_t GTSC_Blcny2[];
extern const uint8_t GTSC_Cave[];
extern const uint8_t GTSC_Cemet[];
extern const uint8_t GTSC_Cent[];
extern const uint8_t GTSC_CentW[];
extern const uint8_t GTSC_Chako[];
extern const uint8_t GTSC_Clock[];
extern const uint8_t GTSC_Comu[];
extern const uint8_t GTSC_Cthu[];
extern const uint8_t GTSC_Cthu2[];
extern const uint8_t GTSC_Curly[];
extern const uint8_t GTSC_CurlyS[];
extern const uint8_t GTSC_Dark[];
extern const uint8_t GTSC_Drain[];
extern const uint8_t GTSC_e_Blcn[];
extern const uint8_t GTSC_e_Ceme[];
extern const uint8_t GTSC_e_Jenk[];
extern const uint8_t GTSC_e_Labo[];
extern const uint8_t GTSC_e_Malc[];
extern const uint8_t GTSC_e_Maze[];
extern const uint8_t GTSC_e_Sky[];
extern const uint8_t GTSC_EgEnd1[];
extern const uint8_t GTSC_EgEnd2[];
extern const uint8_t GTSC_Egg1[];
extern const uint8_t GTSC_Egg6[];
extern const uint8_t GTSC_EggR[];
extern const uint8_t GTSC_EggR2[];
extern const uint8_t GTSC_Eggs[];
extern const uint8_t GTSC_Eggs2[];
extern const uint8_t GTSC_EggX[];
extern const uint8_t GTSC_EggX2[];
extern const uint8_t GTSC_Fall[];
extern const uint8_t GTSC_Frog[];
extern const uint8_t GTSC_Gard[];
extern const uint8_t GTSC_Hell1[];
extern const uint8_t GTSC_Hell2[];
extern const uint8_t GTSC_Hell3[];
extern const uint8_t GTSC_Hell4[];
extern const uint8_t GTSC_Hell42[];
extern const uint8_t GTSC_Island[];
extern const uint8_t GTSC_Itoh[];
extern const uint8_t GTSC_Jail1[];
extern const uint8_t GTSC_Jail2[];
extern const uint8_t GTSC_Jenka1[];
extern const uint8_t GTSC_Jenka2[];
extern const uint8_t GTSC_Kings[];
extern const uint8_t GTSC_Little[];
extern const uint8_t GTSC_Lounge[];
extern const uint8_t GTSC_Malco[];
extern const uint8_t GTSC_Mapi[];
extern const uint8_t GTSC_MazeA[];
extern const uint8_t GTSC_MazeB[];
extern const uint8_t GTSC_MazeD[];
extern const uint8_t GTSC_MazeH[];
extern const uint8_t GTSC_MazeI[];
extern const uint8_t GTSC_MazeM[];
extern const uint8_t GTSC_MazeO[];
extern const uint8_t GTSC_MazeS[];
extern const uint8_t GTSC_MazeW[];
extern const uint8_t GTSC_MiBox[];
extern const uint8_t GTSC_Mimi[];
extern const uint8_t GTSC_Momo[];
extern const uint8_t GTSC_Oside[];
extern const uint8_t GTSC_Ostep[];
extern const uint8_t GTSC_Pens1[];
extern const uint8_t GTSC_Pens2[];
extern const uint8_t GTSC_Pixel[];
extern const uint8_t GTSC_Plant[];
extern const uint8_t GTSC_Pole[];
extern const uint8_t GTSC_Pool[];
extern const uint8_t GTSC_Prefa1[];
extern const uint8_t GTSC_Prefa2[];
extern const uint8_t GTSC_Priso1[];
extern const uint8_t GTSC_Priso2[];
extern const uint8_t GTSC_Ring1[];
extern const uint8_t GTSC_Ring2[];
extern const uint8_t GTSC_Ring3[];
extern const uint8_t GTSC_River[];
extern const uint8_t GTSC_Sand[];
extern const uint8_t GTSC_SandE[];
extern const uint8_t GTSC_Santa[];
extern const uint8_t GTSC_Shelt[];
extern const uint8_t GTSC_Start[];
extern const uint8_t GTSC_Statue[];
extern const uint8_t GTSC_Stream[];
extern const uint8_t GTSC_Weed[];
extern const uint8_t GTSC_WeedB[];
extern const uint8_t GTSC_WeedD[];
extern const uint8_t GTSC_WeedS[];


extern const uint8_t z80_xgm[], z80_xgm_end[];
extern const uint8_t stop_xgm;

extern const uint8_t NPC_TABLE[];
extern const uint8_t BMP_Ascii[];
extern const uint8_t BMP_Kanji[];
extern const uint8_t JStageName[];
extern const uint8_t JCreditStr[];
extern const uint8_t JConfigText[];

extern const uint8_t PAT_MoonTop[];
extern const uint8_t MAP_MoonTop[];
extern const uint8_t PAT_MoonBtm[];
extern const uint8_t MAP_MoonBtm[];
extern const uint8_t PAT_FogTop[];
extern const uint8_t MAP_FogTop[];
extern const uint8_t PAT_FogBtm[];
extern const uint8_t MAP_FogBtm[];
extern const uint8_t PAT_QuakerB[];
extern const uint8_t MAP_QuakerB[];
extern const uint8_t PAT_SndTest[];
extern const uint8_t MAP_SndTest[];

extern const uint8_t PAT_Ill01[];
extern const uint8_t MAP_Ill01[];
extern const uint8_t PAT_Ill02[];
extern const uint8_t MAP_Ill02[];
extern const uint8_t PAT_Ill03[];
extern const uint8_t MAP_Ill03[];
extern const uint8_t PAT_Ill04[];
extern const uint8_t MAP_Ill04[];
extern const uint8_t PAT_Ill05[];
extern const uint8_t MAP_Ill05[];
extern const uint8_t PAT_Ill06[];
extern const uint8_t MAP_Ill06[];
extern const uint8_t PAT_Ill07[];
extern const uint8_t MAP_Ill07[];
extern const uint8_t PAT_Ill08[];
extern const uint8_t MAP_Ill08[];
extern const uint8_t PAT_Ill09[];
extern const uint8_t MAP_Ill09[];
extern const uint8_t PAT_Ill10[];
extern const uint8_t MAP_Ill10[];
extern const uint8_t PAT_Ill11[];
extern const uint8_t MAP_Ill11[];
extern const uint8_t PAT_Ill12[];
extern const uint8_t MAP_Ill12[];

extern const uint8_t PAT_Ill14[];
extern const uint8_t MAP_Ill14[];
extern const uint8_t PAT_Ill15[];
extern const uint8_t MAP_Ill15[];
extern const uint8_t PAT_Ill16[];
extern const uint8_t MAP_Ill16[];
extern const uint8_t PAT_Ill17[];
extern const uint8_t MAP_Ill17[];
extern const uint8_t PAT_Ill18[];
extern const uint8_t MAP_Ill18[];

extern const uint8_t SFX_01[], SFX_01_end[];
extern const uint8_t SFX_02[], SFX_02_end[];
extern const uint8_t SFX_03[], SFX_03_end[];
extern const uint8_t SFX_04[], SFX_04_end[];
extern const uint8_t SFX_05[], SFX_05_end[];
extern const uint8_t SFX_06[], SFX_06_end[];
extern const uint8_t SFX_07[], SFX_07_end[];
extern const uint8_t SFX_08[], SFX_08_end[];
extern const uint8_t SFX_0B[], SFX_0B_end[];
extern const uint8_t SFX_0C[], SFX_0C_end[];
extern const uint8_t SFX_0E[], SFX_0E_end[];
extern const uint8_t SFX_0F[], SFX_0F_end[];
extern const uint8_t SFX_10[], SFX_10_end[];
extern const uint8_t SFX_11[], SFX_11_end[];
extern const uint8_t SFX_12[], SFX_12_end[];
extern const uint8_t SFX_14[], SFX_14_end[];
extern const uint8_t SFX_15[], SFX_15_end[];
extern const uint8_t SFX_16[], SFX_16_end[];
extern const uint8_t SFX_17[], SFX_17_end[];
extern const uint8_t SFX_18[], SFX_18_end[];
extern const uint8_t SFX_19[], SFX_19_end[];
extern const uint8_t SFX_1A[], SFX_1A_end[];
extern const uint8_t SFX_1B[], SFX_1B_end[];
extern const uint8_t SFX_1C[], SFX_1C_end[];
extern const uint8_t SFX_1D[], SFX_1D_end[];
extern const uint8_t SFX_1E[], SFX_1E_end[];
extern const uint8_t SFX_1F[], SFX_1F_end[];
extern const uint8_t SFX_20[], SFX_20_end[];
extern const uint8_t SFX_21[], SFX_21_end[];
extern const uint8_t SFX_22[], SFX_22_end[];
extern const uint8_t SFX_23[], SFX_23_end[];
extern const uint8_t SFX_25[], SFX_25_end[];
extern const uint8_t SFX_26[], SFX_26_end[];
extern const uint8_t SFX_27[], SFX_27_end[];
extern const uint8_t SFX_28[], SFX_28_end[];
extern const uint8_t SFX_2A[], SFX_2A_end[];
extern const uint8_t SFX_2B[], SFX_2B_end[];
extern const uint8_t SFX_2C[], SFX_2C_end[];
extern const uint8_t SFX_2D[], SFX_2D_end[];
extern const uint8_t SFX_2E[], SFX_2E_end[];
extern const uint8_t SFX_2F[], SFX_2F_end[];
extern const uint8_t SFX_30[], SFX_30_end[];
extern const uint8_t SFX_31[], SFX_31_end[];
extern const uint8_t SFX_32[], SFX_32_end[];
extern const uint8_t SFX_33[], SFX_33_end[];
extern const uint8_t SFX_34[], SFX_34_end[];
extern const uint8_t SFX_35[], SFX_35_end[];
extern const uint8_t SFX_36[], SFX_36_end[];
extern const uint8_t SFX_37[], SFX_37_end[];
extern const uint8_t SFX_38[], SFX_38_end[];
extern const uint8_t SFX_39[], SFX_39_end[];
extern const uint8_t SFX_3A[], SFX_3A_end[];
extern const uint8_t SFX_3B[], SFX_3B_end[];
extern const uint8_t SFX_3C[], SFX_3C_end[];
extern const uint8_t SFX_3D[], SFX_3D_end[];
extern const uint8_t SFX_3E[], SFX_3E_end[];
extern const uint8_t SFX_3F[], SFX_3F_end[];
extern const uint8_t SFX_40[], SFX_40_end[];
extern const uint8_t SFX_41[], SFX_41_end[];
extern const uint8_t SFX_46[], SFX_46_end[];
extern const uint8_t SFX_47[], SFX_47_end[];
extern const uint8_t SFX_48[], SFX_48_end[];
extern const uint8_t SFX_64[], SFX_64_end[];
extern const uint8_t SFX_65[], SFX_65_end[];
extern const uint8_t SFX_66[], SFX_66_end[];
extern const uint8_t SFX_67[], SFX_67_end[];
extern const uint8_t SFX_68[], SFX_68_end[];
extern const uint8_t SFX_69[], SFX_69_end[];
extern const uint8_t SFX_6A[], SFX_6A_end[];
extern const uint8_t SFX_6B[], SFX_6B_end[];
extern const uint8_t SFX_6C[], SFX_6C_end[];
extern const uint8_t SFX_6D[], SFX_6D_end[];
extern const uint8_t SFX_6E[], SFX_6E_end[];
extern const uint8_t SFX_6F[], SFX_6F_end[];
extern const uint8_t SFX_70[], SFX_70_end[];
extern const uint8_t SFX_71[], SFX_71_end[];
extern const uint8_t SFX_72[], SFX_72_end[];
extern const uint8_t SFX_73[], SFX_73_end[];
extern const uint8_t SFX_74[], SFX_74_end[];
extern const uint8_t SFX_75[], SFX_75_end[];
extern const uint8_t SFX_96[], SFX_96_end[];
extern const uint8_t SFX_97[], SFX_97_end[];
extern const uint8_t SFX_98[], SFX_98_end[];
extern const uint8_t SFX_99[], SFX_99_end[];
extern const uint8_t SFX_9A[], SFX_9A_end[];
extern const uint8_t SFX_9B[], SFX_9B_end[];
extern const uint8_t SFX_90[], SFX_90_end[];
extern const uint8_t SFX_91[], SFX_91_end[];
extern const uint8_t SFX_92[], SFX_92_end[];
extern const uint8_t SFX_93[], SFX_93_end[];
extern const uint8_t SFX_94[], SFX_94_end[];
extern const uint8_t SFX_95[], SFX_95_end[];
extern const uint8_t SFX_9C[], SFX_9C_end[];
extern const uint8_t SFX_9D[], SFX_9D_end[];
extern const uint8_t SFX_9E[], SFX_9E_end[];
extern const uint8_t SFX_9F[], SFX_9F_end[];

extern const uint8_t BGM_Mischievous[];
extern const uint8_t BGM_Safety[];
extern const uint8_t BGM_GameOver[];
extern const uint8_t BGM_Gravity[];
extern const uint8_t BGM_Grasstown[];
extern const uint8_t BGM_Meltdown2[];
extern const uint8_t BGM_EyesOfFlame[];
extern const uint8_t BGM_Gestation[];
extern const uint8_t BGM_Mimiga[];
extern const uint8_t BGM_Fanfare1[];
extern const uint8_t BGM_Balrog[];
extern const uint8_t BGM_Cemetery[];
extern const uint8_t BGM_Plant[];
extern const uint8_t BGM_Pulse[];
extern const uint8_t BGM_Fanfare2[];
extern const uint8_t BGM_Fanfare3[];
extern const uint8_t BGM_Tyrant[];
extern const uint8_t BGM_Run[];
extern const uint8_t BGM_Jenka1[];
extern const uint8_t BGM_LabFight[];
extern const uint8_t BGM_Access[];
extern const uint8_t BGM_Oppression[];
extern const uint8_t BGM_Geothermal[];
extern const uint8_t BGM_CaveStory[];
extern const uint8_t BGM_MoonSong[];
extern const uint8_t BGM_HerosEnd[];
extern const uint8_t BGM_Scorching[];
extern const uint8_t BGM_Quiet[];
extern const uint8_t BGM_LastCave[];
extern const uint8_t BGM_Balcony[];
extern const uint8_t BGM_Charge[];
extern const uint8_t BGM_LastBoss[];
extern const uint8_t BGM_WayBackHome[];
extern const uint8_t BGM_Zombie[];
extern const uint8_t BGM_Breakdown[];
extern const uint8_t BGM_RunningHell[];
extern const uint8_t BGM_Jenka2[];
extern const uint8_t BGM_Waterway[];
extern const uint8_t BGM_SealChamber[];
extern const uint8_t BGM_Toroko[];
extern const uint8_t BGM_White[];
extern const uint8_t BGM_TimeTable[];

extern const uint8_t LS_00[];
extern const uint8_t LS_01[];
extern const uint8_t LS_02[];
extern const uint8_t LS_03[];
extern const uint8_t LS_04[];
extern const uint8_t LS_05[];
extern const uint8_t LS_06[];
extern const uint8_t LS_07[];
extern const uint8_t LS_08[];
extern const uint8_t LS_09[];
extern const uint8_t LS_10[];
extern const uint8_t LS_11[];
extern const uint8_t LS_12[];
extern const uint8_t LS_13[];
extern const uint8_t LS_14[];
extern const uint8_t LS_15[];
extern const uint8_t LS_16[];
extern const uint8_t LS_17[];
extern const uint8_t LS_18[];
extern const uint8_t LS_19[];
extern const uint8_t LS_20[];
extern const uint8_t LS_21[];
